import {env} from 'cloudflare:workers';
import {catalog} from './catalog';
import {db,one,rows,id,now} from './db';
export type FeedItem={title:string;url:string;date:string|null};
export function cleanText(value:string){return value.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/\s+/g,' ').trim();}
export function parseFeed(xml:string,base:string,scope?:string):FeedItem[]{const blocks=xml.match(/<(item|entry)\b[^>]*>[\s\S]*?<\/(?:item|entry)>/gi)||[];return blocks.slice(0,500).flatMap(block=>{const title=cleanText(block.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i)?.[1]||'').slice(0,220);const raw=cleanText(block.match(/<link\b[^>]*>([\s\S]*?)<\/link>/i)?.[1]||block.match(/<link\b[^>]*href=["']([^"']+)["']/i)?.[1]||'');const dateRaw=cleanText(block.match(/<(?:pubDate|published|updated)\b[^>]*>([\s\S]*?)<\/(?:pubDate|published|updated)>/i)?.[1]||'');try{const url=new URL(raw,base);if(!title||!raw||url.protocol!=='https:')return [];const parsed=Date.parse(dateRaw);return [{title,url:url.href,date:Number.isFinite(parsed)?new Date(parsed).toISOString():null}];}catch{return [];}}).filter(item=>{if(scope!=='chatgpt-apps')return true;const u=new URL(item.url);return ((u.hostname==='developers.openai.com'&&u.pathname.replace(/\/$/,'')==='/codex/changelog')||(u.hostname==='learn.chatgpt.com'&&u.pathname.replace(/\/$/,'')==='/docs/changelog'))&&/^#codex-\d{4}-\d{2}-\d{2}-(app|mobile)$/.test(u.hash);}).sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,15);}
async function boundedFetch(url:string,etag?:string|null){let current=url;for(let i=0;i<5;i++){const u=new URL(current);if(u.protocol!=='https:'||/^(localhost|127\.|10\.|192\.168\.|169\.254\.|0\.|\[)/.test(u.hostname))throw new Error('Unsupported source address');const r=await fetch(current,{headers:{'User-Agent':'AIs source checker/1.0',...etag?{'If-None-Match':etag}:{}},redirect:'manual',signal:AbortSignal.timeout(7000)});if(r.status>=300&&r.status<400&&r.status!==304){current=new URL(r.headers.get('location')||'',current).href;await r.body?.cancel();continue;}if(r.status===304)return {response:r,data:new Uint8Array()};if(!r.ok)throw new Error('HTTP '+r.status);const reader=r.body?.getReader();let size=0;const chunks:Uint8Array[]=[];if(reader){try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>1500000)throw new Error('Source exceeds size limit');chunks.push(value);}}finally{await reader.cancel();}}const data=new Uint8Array(size);let off=0;for(const c of chunks){data.set(c,off);off+=c.length;}return {response:r,data};}throw new Error('Too many redirects');}
async function hash(data:Uint8Array){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(data).buffer))].map(v=>v.toString(16).padStart(2,'0')).join('');}
export async function syncTool(toolId:string){const t=catalog.find(t=>t.id===toolId);if(!t)throw new Error('Unknown tool');let changed=0,errors=0;for(const type of ['content','logo'] as const){const key=t.id+':'+type,url=type==='logo'?t.logoSource:t.feedUrl||t.latestUpdate.sourceUrl;const old=await one<{url:string;etag:string|null;content_hash:string|null;changed_at:string|null;payload:string|null;status:string}>('SELECT url,etag,content_hash,changed_at,payload,status FROM source_snapshots WHERE id=?',key);let previous:{needsReview?:boolean;lastSuccessAt?:string}={};try{previous=old?.payload?JSON.parse(old.payload):{};}catch{}const reviewPending=old?.status==='review_needed'||previous.needsReview===true;try{const {response,data}=await boundedFetch(url,old?.url===url?old.etag:null);if(response.status===304){if(!old?.content_hash||old.url!==url)throw new Error('Invalid cache response');const stamp=now();await db().prepare("UPDATE source_snapshots SET checked_at=?,status=?,payload=?,error=NULL WHERE id=?").bind(stamp,reviewPending?'review_needed':'current',JSON.stringify({...previous,lastSuccessAt:stamp}),key).run();continue;}const text=type==='content'?new TextDecoder().decode(data):'',digest=await hash(type==='content'?new TextEncoder().encode(cleanText(text)):data),isChanged=old?.url===url&&!!old?.content_hash&&old.content_hash!==digest;const stamp=now();let payload:string|null=null;
if(type==='logo'){const mime=response.headers.get('content-type')?.split(';')[0]||'';if(!/^image\/(png|jpeg|webp|svg\+xml|x-icon|vnd\.microsoft\.icon|avif)$/.test(mime))throw new Error('Unsupported logo type');if(env.BUCKET)await env.BUCKET.put('logos/'+t.id,data,{customMetadata:{source:url},httpMetadata:{contentType:mime,cacheControl:'public, max-age=3600'}});payload=JSON.stringify({mime,lastSuccessAt:stamp});}
else{const items=t.feedUrl?parseFeed(text,url,t.feedScope):[];const title=cleanText(text.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||t.latestUpdate.title).slice(0,240);payload=JSON.stringify({title,items,lastSuccessAt:stamp,needsReview:reviewPending||!t.feedUrl&&isChanged,kind:t.feedUrl?'feed':'page'});}
await db().prepare('INSERT INTO source_snapshots(id,url,etag,content_hash,title,checked_at,changed_at,status,error,payload) VALUES(?,?,?,?,?,?,?,?,NULL,?) ON CONFLICT(id) DO UPDATE SET url=excluded.url,etag=excluded.etag,content_hash=excluded.content_hash,title=excluded.title,checked_at=excluded.checked_at,changed_at=excluded.changed_at,status=excluded.status,error=NULL,payload=excluded.payload').bind(key,url,response.headers.get('etag'),digest,t.name,stamp,isChanged?stamp:old?.changed_at||null,type==='content'&&(reviewPending||!t.feedUrl&&isChanged)?'review_needed':'current',payload).run();if(isChanged)changed++;
}catch(e){errors++;await db().prepare('INSERT INTO source_snapshots(id,url,title,checked_at,status,error) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET checked_at=excluded.checked_at,status=excluded.status,error=excluded.error').bind(key,url,t.name,now(),'error',(e as Error).message.slice(0,200)).run();}}
return {changed,errors};}
export async function syncBatch(force=false){const recent=await one<{started_at:string}>('SELECT started_at FROM sync_runs ORDER BY started_at DESC LIMIT 1');if(recent&&Date.now()-Date.parse(recent.started_at)<(force?60000:3600000))return {skipped:true};const lease=await db().prepare("INSERT INTO source_snapshots(id,url,checked_at,status) VALUES('__sync_lock','',?,'lock') ON CONFLICT(id) DO UPDATE SET checked_at=excluded.checked_at WHERE source_snapshots.checked_at<?").bind(now(),new Date(Date.now()-60000).toISOString()).run();if(!lease.meta.changes)return {skipped:true};const run=id(),stamp=now();await db().prepare("INSERT INTO sync_runs(id,started_at,status,checked,changed,errors) VALUES(?,?,'running',0,0,0)").bind(run,stamp).run();let changed=0,errors=0;const snapshots=await rows<{id:string;checked_at:string}>('SELECT id,checked_at FROM source_snapshots');const order=catalog.slice().sort((a,b)=>(snapshots.find(s=>s.id===a.id+':content')?.checked_at||'').localeCompare(snapshots.find(s=>s.id===b.id+':content')?.checked_at||''));const batch=order.slice(0,3);const results=await Promise.all(batch.map(t=>syncTool(t.id)));for(const r of results){changed+=r.changed;errors+=r.errors;}await db().prepare('UPDATE sync_runs SET finished_at=?,status=?,checked=?,changed=?,errors=? WHERE id=?').bind(now(),errors?'partial':'complete',batch.length,changed,errors,run).run();return {checked:batch.length,changed,errors};}
export async function liveFeed(){try{const sources=await rows<{id:string;payload:string;checked_at:string;status:string}>("SELECT id,payload,checked_at,status FROM source_snapshots WHERE payload IS NOT NULL AND id LIKE '%:content'");return sources.flatMap(s=>{const p=JSON.parse(s.payload);return (p.items||[]).map((i:FeedItem)=>({...i,toolId:s.id.replace(':content',''),checkedAt:p.lastSuccessAt||(s.status==='error'?null:s.checked_at),stale:s.status==='error'}));}).sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,30);}catch{return [];}}
