import { brand } from "@/lib/brand";

/**
 * 화면 문구 단일 출처.
 *
 * 이전에는 ko/en 이중 사전이었지만, 라벨만 번역되고 리뷰 본문 10개는 전부 한국어라
 * 영어 화면은 반쯤 번역된 상태로 보였습니다. 비용은 전부 내면서 값은 못 받는 구조였고,
 * 실제로 영어 모드에서는 문제 클릭 시 결과가 0건이었습니다.
 *
 * 지금은 한국어 단일입니다. 문자열을 여기 모아두는 것 자체는 그대로 유지합니다 —
 * 문제였던 건 문자열 테이블이 아니라 반쪽짜리 이중 언어였습니다.
 */
export const copy = {
    navHome: "홈",
    navCommunity: "커뮤니티",
    navSearch: "도구 찾기",
    navAbout: "평가 기준",
    footer: `${brand.name} — ${brand.oneLiner}`,
    heroTitle: "고르기 전에, 떨어뜨리세요.",
    heroDesc:
      "겪고 있는 문제를 고르면 후보 3~5개가 나옵니다. 각각 이 문제에서 되는 것과 안 되는 것, 우리 규모에 맞는지, 나갈 때 얼마나 드는지를 나란히 놓고 봅니다.",
    heroCta: "내 문제부터 고르기 →",
    principlesTitle: "이 사이트가 지키는 것",
    principles: [
      {
        title: "점수마다 근거를 답니다",
        description: "왜 그 숫자인지 못 쓰겠으면 점수를 매기지 않습니다. 근거는 화면에 그대로 노출되고, 다르게 보시면 반박할 수 있습니다."
      },
      {
        title: "안 되는 것을 먼저 씁니다",
        description: "결정권자가 가장 먼저 하는 건 고르기가 아니라 떨어뜨리기입니다. 그래서 \"이런 경우엔 쓰지 마세요\"가 맨 위에 있습니다."
      },
      {
        title: "확인 안 된 건 비워둡니다",
        description: "변경 이력이든 가격 확인 시점이든, 확인하지 못한 것은 지어내지 않고 비운 채로 그렇게 표시합니다."
      }
    ],
    problemTitle: "어떤 문제를 겪고 계신가요",
    problemDesc: "문제를 고르면 후보가 좁혀지고, 카드마다 이 문제에서의 한계까지 함께 보입니다.",
    featuredTitle: "지금 정리되어 있는 도구",
    featuredDesc: "총점이 높은 순입니다. 다만 총점보다 \"우리 규모에 맞는지\"와 \"쓰지 말아야 할 조건\"이 먼저 봐야 할 정보입니다.",
    aboutTitle: `${brand.name} 소개`,
    aboutDesc:
      "도구 선택은 기능 목록 비교가 아니라 포기할 것을 정하는 일입니다. 여기서는 같은 문제에 걸리는 후보들을 같은 기준으로 놓고, 각각 무엇을 포기하게 되는지를 함께 적습니다.",
    aboutDiffTitle: "별점 사이트와 다른 점",
    searchTitle: "카테고리보다 상황으로 검색하세요",
    searchDesc: "겪고 있는 문제를 고르면 후보가 좁혀지고, 카드마다 그 문제에서의 한계까지 함께 보입니다.",
    searchLoading: "검색 필터를 불러오는 중...",
    searchFilterAria: "도구 검색 및 필터",
    searchPanelTitle: "겪고 있는 문제부터 고르세요",
    searchPanelDesc: "문제를 고르면 후보가 3~5개로 좁혀지고, 카드마다 이 문제에서 되는 것과 안 되는 것이 함께 보입니다.",
    badgeDesc: [
      "불필요한 반복을 줄여 실행 속도를 높입니다.",
      "설정과 운영 원칙이 없으면 품질 저하가 생길 수 있습니다.",
      "데이터 이동 비용이나 전환 비용이 높습니다."
    ],
    teamSizeLegend: "팀 규모",
    teamSizeHint: "해당 규모에서 권하지 않는 도구는 결과에서 빠집니다.",
    compareHint: "후보를 2~3개 담으면 나란히 놓고 비교할 수 있습니다.",
    compareAdd: "비교 담기",
    compareRemove: "담김",
    compareSelected: "비교 담기",
    compareClear: "비우기",
    compareGo: "나란히 비교 →",
    compareNeedTwo: "2개 이상 담아야 비교할 수 있습니다",
    compareTrayAria: "비교 담은 도구",
    compareTitle: "나란히 비교",
    compareDesc: "같은 기준으로 놓고 봐야 무엇을 포기하는지가 보입니다.",
    compareForProblem: "이 문제 기준:",
    compareAngleRow: "이 문제에서",
    compareNotMapped: "이 문제에 매핑되지 않은 도구입니다.",
    compareEmptyDesc: "검색 화면에서 후보를 담은 뒤 다시 오세요.",
    compareGoSearch: "도구 찾으러 가기 →",
    compareFoot: "점수와 판단은 편집 기준에 따른 것이며, 도입 전 자사 환경에서 직접 확인하시길 권합니다.",
    teamFitRow: "팀 규모별 적합도",
    doNotUseRow: "이런 경우엔 쓰지 마세요",
    pricingRow: "가격 구조",
    pricingSpike: "비용이 튀는 조건",
    asOf: "기준",
    asOfUnknown: "가격 확인 시점 미기재",
    adoptionRow: "도입에 드는 시간",
    costGroupTitle: "도입·가격·이탈 비용",
    costGroupHint: "3개 항목",
    timeToValue: "첫 효용까지",
    timeToSettle: "규칙이 굳기까지",
    exitRow: "나갈 때의 비용",
    exitLevels: { easy: "이탈 쉬움", manageable: "감당 가능", hard: "이탈 어려움", trapped: "사실상 묶임" },
    fitFits: "적합",
    fitConditional: "조건부",
    fitAvoid: "권하지 않음",
    reviewUnverified: "아직 검수되지 않은 초안입니다. 도입 결정에 쓰기 전 직접 확인하세요.",
    reviewedBy: "검수",
    evidenceKinds: {
      "hands-on": "직접 사용",
      "team-deployment": "팀 도입 경험",
      "user-interview": "사용자 인터뷰",
      "vendor-doc": "공식 문서",
      "public-incident": "공개된 장애/사건"
    },
    pricingStale: "가격 정보는 가장 빨리 바뀝니다. 반드시 공식 페이지에서 다시 확인하세요.",
    ctxWhy: "같은 판단이라도 어떤 처지에서 나온 건지가 정보입니다. 신원은 묻지 않습니다.",
    ctxRole: "역할",
    ctxTeamSize: "팀 규모",
    ctxDuration: "사용 기간",
    ctxRequired: "역할·팀 규모·사용 기간을 모두 골라주세요.",
    roleLabels: {
      practitioner: "실무자",
      "team-lead": "팀 리드",
      "decision-maker": "결정권자",
      admin: "IT·보안",
      solo: "1인"
    },
    teamSizeLabels: { "1-5": "1~5인", "6-30": "6~30인", "30+": "30인 이상" },
    durationLabels: {
      "evaluated-only": "검토만 함",
      "under-1m": "1개월 미만",
      "1-6m": "1~6개월",
      "6m-2y": "6개월~2년",
      "2y+": "2년 이상"
    },
    dissentTitle: "점수 근거와 이의",
    dissentSummaryHint: "5개 항목",
    dissentDesc: "각 점수에 왜 그 숫자인지 적었습니다. 다르게 보신다면 근거와 함께 알려주세요.",
    dissentDirections: { agree: "동의", "too-low": "더 낮다", "too-high": "더 높다" },
    dissentReasonLabel: "그렇게 보신 이유",
    dissentReasonPlaceholder: "실제로 어떤 상황에서 그렇게 느끼셨는지 적어주세요.",
    dissentNeedReason: "다르게 보신 이유를 20자 이상 적어주세요.",
    dissentSubmit: "의견 남기기",
    dissentThanks: "남겨주셔서 고맙습니다. 검토 후 점수에 반영될 수 있습니다.",
    dissentEmpty: "아직 이 항목에 대한 의견이 없습니다. 첫 의견은 이 도구 상단에 인용으로 고정됩니다.",
    decisionTitle: "도입 결정 기록",
    decisionDesc: "무엇 대신 이걸 골랐고, 지금도 쓰고 있는지. 별점보다 이 기록이 판단에 도움이 됩니다.",
    decisionEmpty: "아직 기록이 없습니다.",
    decisionFirstPerk: "첫 기록은 이 도구 상세 상단에 인용으로 고정됩니다.",
    decisionAdd: "내 도입 결정 기록하기",
    decisionSubmit: "기록 남기기",
    decisionThanks: "기록해주셔서 고맙습니다. 3개월 뒤에 '지금도 쓰시나요'를 여쭤보겠습니다.",
    decisionConsidered: "함께 검토:",
    decisionConsideredLabel: "함께 검토했던 대안 (쉼표로 구분)",
    decisionConsideredPlaceholder: "예: Linear, Jira",
    decisionWhyLabel: "이걸 고른 이유",
    decisionWhyPlaceholder: "무엇이 결정적이었나요?",
    decisionNeedWhy: "고른 이유를 15자 이상 적어주세요.",
    decisionWhenLabel: "도입 시점 (YYYY-MM)",
    decisionNeedDate: "도입 시점을 YYYY-MM 형식으로 적어주세요.",
    decisionOutcomeLabel: "지금 상태",
    decisionAdopted: "도입",
    decisionChecked: "확인됨",
    decisionStale: "6개월 이상 미확인",
    outcomeLabels: { "still-using": "계속 씀", reduced: "축소함", stopped: "그만둠" },
    editorBadge: "편집팀",
    saving: "저장 중…",
    cancel: "취소",
    saveFailed: "저장하지 못했습니다. 잠시 후 다시 시도해주세요.",
    requiredOwner: "붙어야 하는 사람",
    firstMonthRisk: "첫 달의 위험",
    exportReality: "내보내면 실제로",
    whatYouLose: "잃는 것",
    switchWindow: "이전에 걸리는 시간",
    reviewMetaTitle: "이 리뷰의 근거",
    breakageTitle: "이 도구 때문에 업무가 막힌 적 있나요",
    breakageDesc: "제보는 바로 공개되지 않습니다. 검수 후 변경 이력에 반영되며 제보자 크레딧이 붙습니다.",
    breakageAdd: "고장 제보하기",
    breakageSubmit: "제보 보내기",
    breakageThanks: "제보 고맙습니다. 확인 후 변경 이력에 반영되면 크레딧을 붙여 공개합니다.",
    breakageWhenLabel: "언제 (YYYY-MM)",
    breakageWhatLabel: "무엇이 안 됐나요",
    breakageWhatPlaceholder: "어떤 작업이 어떻게 막혔는지 구체적으로 적어주세요.",
    breakageWorkaroundLabel: "우회 방법이 있었나요 (선택)",
    breakageWorkaround: "우회:",
    breakageCredit: "제보",
    breakageNeedDetail: "무엇이 안 됐는지 15자 이상 적어주세요.",
    qKindLowScore: "낮게 준 점수",
    qKindNoHistory: "변경 이력 없음",
    qKindWorstCase: "최악 시나리오",
    qAll: "전체",
    qFilterAria: "질문 종류 필터",
    qNoAnswers: "응답 0",
    qOurTake: "우리가 본 것",
    qAnswerCta: "이 도구에서 답하기 →",
    qFirstPerk: "각 질문의 첫 응답은 해당 도구 상세 상단에 인용으로 고정됩니다.",
    searchKeyword: "키워드 검색",
    searchKeywordPlaceholder: "예: 작업 분산, 전략 워크숍",
    searchProblem: "문제 상황 검색",
    searchFilterLegend: "판단 배지로 필터링",
    clearFilters: "필터 초기화",
    results: "검색 결과",
    matchCount: "개 도구가 현재 조건에 맞습니다.",
    noMatch: "일치하는 결과가 없습니다",
    noMatchDesc: "문제 문장을 바꾸거나 배지 필터를 줄여서 다시 검색해보세요.",
    readReview: "리뷰 상세 보기 →",
    whyExists: "이 도구가 필요한 이유",
    relatedTools: "함께 비교할 도구",
    alternatives: "대안 도구",
    bestCase: "최선의 시나리오",
    worstCase: "최악의 시나리오",
    verdict: ["시간 절약", "신중한 사용", "락인 위험"],
    comparisonTitle: "비슷한 툴 비교 (되는 것 / 안 되는 것)",
    comparisonDesc: "대안 도구를 실제로 놓고 봤을 때, 어디서 앞서고 어디서 밀리는지 정리했습니다.",
    comparisonTarget: "비교 대상",
    comparisonBetter: "더 잘되는 점",
    comparisonWorse: "약한 점",
    scoreTitle: "리뷰 총점",
    scoreBasisNote: "항목마다 점수를 준 근거를 함께 적었습니다.",
    patchTitle: "굵직한 패치 / 에러 변경사항",
    patchDesc: "도입 판단에 영향을 준 확인된 변경만 기록합니다.",
    patchChange: "변경사항",
    patchRisk: "에러/리스크",
    patchEmpty: "아직 확인된 변경 이력이 없습니다. 검증되지 않은 항목은 넣지 않습니다.",
    patchImpactHigh: "영향도 높음",
    patchImpactMedium: "영향도 보통",
    patchImpactLow: "영향도 낮음",
    reviewSummary: "한줄 총평",
    reviewWrite: "리뷰 남기기",
    nickname: "닉네임",
    oneLine: "한줄 리뷰",
    detail: "상세 리뷰",
    rating: "평점",
    saveReview: "리뷰 등록",
    saved: "저장됨",
    reviewList: "등록된 리뷰",
    firstReview: "아직 등록된 리뷰가 없습니다.",
    reviewLocalOnly: "지금은 작성한 리뷰가 이 브라우저에만 저장됩니다. 다른 사람에게는 보이지 않습니다.",
    anonymous: "익명",
    nicknamePlaceholder: "예: PM_anna",
    oneLinePlaceholder: "예: 협업 속도는 빨랐고, 온보딩도 쉬웠어요.",
    detailPlaceholder: "실무에서 어떤 상황에서 도움이 됐는지 남겨보세요.",
    workGuide: "실무 사용 추천 가이드",
    howToUse: "어떻게 쓰나",
    tips: "추천 팁",
    scoreLabels: ["기능 완성도", "UI/UX", "에러/안정성", "쾌적도", "가격 합리성"],
    communityHeadline: "우리가 아직 확인하지 못한 것들",
    communitySubline: "리뷰마다 근거를 적었지만 확인하지 못한 부분이 있습니다. 겪어보신 분의 답이 필요합니다.",
  } as const;

export type Copy = typeof copy;
