import {sql} from 'drizzle-orm';
import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const privateRecords=sqliteTable('private_records',{
  id:text('id').primaryKey(),userId:text('user_id').notNull(),kind:text('kind').notNull(),target:text('target'),payload:text('payload').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),
},t=>[index('private_owner_kind').on(t.userId,t.kind),uniqueIndex('private_owner_target').on(t.userId,t.kind,t.target),uniqueIndex('private_payment_occurrence').on(t.userId,sql`json_extract(${t.payload},'$.plannedKey')`).where(sql`${t.kind}='payment' AND json_extract(${t.payload},'$.plannedKey') IS NOT NULL AND json_extract(${t.payload},'$.plannedKey')!=''`)]);
export const posts=sqliteTable('posts',{
  id:text('id').primaryKey(),userId:text('user_id').notNull(),author:text('author').notNull(),kind:text('kind').notNull(),toolId:text('tool_id'),parentId:text('parent_id'),title:text('title').notNull(),body:text('body').notNull(),task:text('task'),plan:text('plan'),usedAt:text('used_at'),affiliation:text('affiliation').notNull().default('none'),ratings:text('ratings'),status:text('status').notNull().default('published'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),
},t=>[index('posts_tool_created').on(t.toolId,t.createdAt),index('posts_parent').on(t.parentId),index('posts_owner').on(t.userId)]);
export const reactions=sqliteTable('reactions',{id:text('id').primaryKey(),userId:text('user_id').notNull(),postId:text('post_id').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('reaction_user_post').on(t.userId,t.postId)]);
export const reports=sqliteTable('reports',{id:text('id').primaryKey(),userId:text('user_id').notNull(),targetId:text('target_id').notNull(),reason:text('reason').notNull(),status:text('status').notNull().default('received'),createdAt:text('created_at').notNull()},t=>[uniqueIndex('report_user_target').on(t.userId,t.targetId)]);
export const notifications=sqliteTable('notifications',{id:text('id').primaryKey(),userId:text('user_id').notNull(),sourceKey:text('source_key').notNull(),metadata:text('metadata'),title:text('title').notNull(),body:text('body').notNull(),href:text('href').notNull(),read:integer('read').notNull().default(0),createdAt:text('created_at').notNull()},t=>[index('notification_owner').on(t.userId),uniqueIndex('notification_unique').on(t.userId,t.sourceKey)]);
export const sources=sqliteTable('source_snapshots',{id:text('id').primaryKey(),url:text('url').notNull(),etag:text('etag'),contentHash:text('content_hash'),title:text('title'),checkedAt:text('checked_at'),changedAt:text('changed_at'),status:text('status').notNull(),error:text('error'),payload:text('payload')});
export const syncRuns=sqliteTable('sync_runs',{id:text('id').primaryKey(),startedAt:text('started_at').notNull(),finishedAt:text('finished_at'),status:text('status').notNull(),checked:integer('checked').notNull().default(0),changed:integer('changed').notNull().default(0),errors:integer('errors').notNull().default(0)});
export const emailOutbox=sqliteTable('email_outbox',{id:text('id').primaryKey(),userId:text('user_id').notNull(),notificationId:text('notification_id').notNull(),status:text('status').notNull().default('queued'),attempts:integer('attempts').notNull().default(0),createdAt:text('created_at').notNull(),sentAt:text('sent_at'),error:text('error'),deliveryId:text('delivery_id'),providerId:text('provider_id')},t=>[uniqueIndex('email_notification').on(t.notificationId),index('email_owner_delivery').on(t.userId,t.deliveryId)]);
export const emailDeliveries=sqliteTable('email_deliveries',{
 id:text('id').primaryKey(),userId:text('user_id').notNull(),settingsId:text('settings_id').notNull(),settingsRevision:text('settings_revision').notNull(),mode:text('mode').notNull(),timeZone:text('time_zone').notNull(),localTime:text('local_time').notNull(),localDate:text('local_date').notNull(),items:text('items').notNull(),payload:text('payload').notNull(),status:text('status').notNull().default('prepared'),attempts:integer('attempts').notNull().default(0),attemptToken:text('attempt_token'),createdAt:text('created_at').notNull(),firstAttemptAt:text('first_attempt_at'),lastAttemptAt:text('last_attempt_at'),nextAttemptAt:text('next_attempt_at'),acceptedAt:text('accepted_at'),providerId:text('provider_id'),cancelRequestedAt:text('cancel_requested_at'),error:text('error'),
},t=>[index('email_delivery_owner_status').on(t.userId,t.status),index('email_delivery_quota').on(t.userId,t.firstAttemptAt)]);
export const emailDispatchState=sqliteTable('email_dispatch_state',{
 userId:text('user_id').primaryKey(),claimToken:text('claim_token'),leaseUntil:text('lease_until').notNull(),nextDigestNotBefore:text('next_digest_not_before'),lastDigestDate:text('last_digest_date'),lastDigestOutcome:text('last_digest_outcome'),updatedAt:text('updated_at').notNull(),
});
export const feedbackSessions=sqliteTable('feedback_sessions',{
  id:text('id').primaryKey(),sessionHash:text('session_hash').notNull(),userId:text('user_id'),scope:text('scope').notNull(),questionVersion:text('question_version').notNull(),context:text('context').notNull(),answer:text('answer'),comment:text('comment').notNull().default(''),startedAt:text('started_at').notNull(),answeredAt:text('answered_at'),updatedAt:text('updated_at').notNull(),
},t=>[uniqueIndex('feedback_session_question').on(t.sessionHash,t.scope,t.questionVersion),index('feedback_owner').on(t.userId),index('feedback_cohort').on(t.questionVersion,t.startedAt)]);

export const notificationCards=sqliteTable('notification_cards',{id:text('id').primaryKey(),userId:text('user_id').notNull(),cardKey:text('card_key').notNull(),hideTopic:text('hide_topic').notNull(),latestNotificationId:text('latest_notification_id').notNull(),sourceVersion:text('source_version').notNull(),sourceRevision:integer('source_revision').notNull(),snapshot:text('snapshot').notNull(),status:text('status').notNull(),emailReason:text('email_reason').notNull(),legacyBaselineVersion:text('legacy_baseline_version'),read:integer('read').notNull().default(0),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('notification_card_owner_key').on(t.userId,t.cardKey)]);
export const noticeSourceHeads=sqliteTable('notice_source_heads',{cardKey:text('card_key').primaryKey(),revision:integer('revision').notNull(),eventRevision:integer('event_revision').notNull(),version:text('version').notNull(),conflict:integer('conflict').notNull().default(0),updatedAt:text('updated_at').notNull()});
