'use client';
import {useState} from 'react';
import {billingReport,horizonEndDate,today,money,type Contract,type Payment} from '@/lib/billing';
import type {PrivateRecord} from './RecordForm';

export default function BillingReport({records}:{records:PrivateRecord[]}){
 const [range,setRange]=useState({from:today().slice(0,7)+'-01',until:horizonEndDate(today(),3)}),[error,setError]=useState('');
 const contracts=records.filter(r=>r.kind==='subscription').map(r=>({id:r.id,...r.payload} as Contract)),payments=records.filter(r=>r.kind==='payment').map(r=>({id:r.id,...r.payload} as Payment));
 let report:ReturnType<typeof billingReport>;try{report=billingReport(contracts,payments,range.from,range.until);}catch{return <p className="error" role="alert">금액이 계산 범위를 벗어났습니다. 구독·결제 기록을 확인해주세요.</p>;}const amounts=(values:Record<string,number>)=>Object.entries(values).map(([c,n])=>money(n,c)).join(' · ')||'확인된 금액 없음';
 return <section className="line-section"><div className="section-heading"><h3>기간별 지출과 청구 확인</h3></div>
  <form className="filters" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget),from=String(data.get('from')),until=String(data.get('until'));try{if(until>horizonEndDate(from,120))throw new Error('조회 기간은 최대 10년입니다.');billingReport(contracts,payments,from,until);setRange({from,until});setError('');}catch(e){setError((e as Error).message);}}}>
   <label className="field">시작일<input type="date" required name="from" defaultValue={range.from}/></label><label className="field">종료일<input type="date" required name="until" defaultValue={range.until}/></label><button className="button secondary small">기간 적용</button>
  </form>{error&&<p className="error" role="alert">{error}</p>}
  <p className="sr-only" role="status">{range.from}부터 {range.until}까지 청구 일정 {report.schedule.length}건을 표시합니다.</p><p className="metadata" style={{marginBottom:18}}>{range.from} ~ {range.until} · 한국 날짜 기준 · 통화별 계산</p>
  <div className="grid-3"><div className="money-card"><small>기간 내 실제 순지출</small><strong style={{fontSize:22}}>{amounts(report.actual)}</strong><p>직접 기록한 결제 − 환불</p></div><div className="money-card"><small>남은 예상 청구</small><strong style={{fontSize:22}}>{amounts(report.remaining)}</strong><p>오늘 이후 · 결제 연결 전</p></div><div className="money-card"><small>실제 + 남은 예상</small><strong style={{fontSize:22}}>{amounts(report.forecast)}</strong><p>미확인 조건은 합계에서 제외</p></div></div>
  <p className="note" style={{margin:'16px 0'}}>실제 결제를 등록할 때 ‘연결할 예정 청구일’을 선택하면 해당 청구는 예상 합계에서 빠집니다. 환불은 반영일의 실제 지출에서 차감하며, 원래 청구를 다시 예상에 넣지 않습니다. 조건 이력이 있는 계약은 청구일에 적용된 조건을 사용합니다. 이력이 없는 이전 기록은 현재 조건을 적용한 참고값입니다. 최초로 확인한 조건 이전의 예상 금액은 채우지 않습니다.</p>
  {(report.unconfirmed>0||report.summary.unknownRenewal>0||report.summary.unknownPause>0)&&<p className="note warning">지난 청구 중 결제 여부 미확인 {report.unconfirmed}회 · 갱신 상태 미확인 {report.summary.unknownRenewal}건 · 일시중지 청구 조건 미확인 {report.summary.unknownPause}건. 실제 지출·남은 예상 합계에 포함하지 않았습니다.</p>}
  {(report.summary.unknownHistory>0||report.summary.pendingTerms>0||report.summary.conflictingHistory>0)&&<p className="note warning">이전 조건 미확인 {report.summary.unknownHistory}건 · 적용일 확인 대기 {report.summary.pendingTerms}건 · 번들 조건 충돌 {report.summary.conflictingHistory}건. 알 수 없는 금액을 0으로 처리하지 않습니다.</p>}
  {(report.summary.unknownFutureAmounts>0||report.summary.unknownTax>0||report.summary.variable>0)&&<p className="note warning">예정 금액 미확인 {report.summary.unknownFutureAmounts}회 · 세금 미확인 {report.summary.unknownTax}건 · 사용량 과금 {report.summary.variable}건. 확인되지 않은 세금·추가 사용료는 합계에 포함되지 않습니다.</p>}
  <div className="table-scroll" tabIndex={0} role="region" aria-label="예정 청구와 결제 연결 표" style={{marginTop:20}}><table className="data-table billing-schedule"><thead><tr><th>청구 예정일</th><th>구독</th><th>예상 금액</th><th>결제 확인</th></tr></thead><tbody>{report.schedule.map(d=><tr key={d.key}><td>{d.date}</td><td>{contracts.find(c=>c.id===d.contractId)&&records.find(r=>r.id===d.contractId)?.payload.name}</td><td>{d.amount==null?'금액 미확인':money(d.amount,d.currency)}{d.versionId&&<p className="metadata">{d.state==='confirmed'?'연결 당시 청구 조건':'날짜별 조건 적용'}</p>}</td><td>{d.state==='confirmed'?<><span className="badge green">결제 연결됨</span><p className="metadata">실제 {d.actualDate} · {money(d.actualAmount!,d.actualCurrency!)}{d.difference!=null&&d.difference!==0?' · 차이 '+money(d.difference,d.currency):''}</p></>:<span className={'badge '+(d.state==='unconfirmed'?'yellow':'gray')}>{d.state==='unconfirmed'?'결제 여부 미확인':'예정 · 미연결'}</span>}</td></tr>)}</tbody></table></div>{!report.schedule.length&&<p className="note">현재 조건으로 확인되는 청구 일정이 없습니다. 날짜·주기·잔여 청구 조건을 확인하세요.</p>}
  <details style={{marginTop:20}}><summary>월별 합계와 내 부담액</summary><div className="table-scroll" tabIndex={0} role="region" aria-label="월별 지출 표"><table className="data-table"><thead><tr><th>월</th><th>실제 순지출</th><th>남은 예상 청구</th></tr></thead><tbody>{Object.entries(report.monthly).sort(([a],[b])=>a.localeCompare(b)).map(([month,v])=><tr key={month}><td>{month}</td><td>{amounts(v.actual)}</td><td>{amounts(v.expected)}</td></tr>)}</tbody></table></div><div className="grid-3" style={{marginTop:20}}><div className="money-card"><small>실제 개인 순지출</small><strong style={{fontSize:20}}>{amounts(report.personalActual)}</strong><p>기록한 내 부담 − 내 환불액</p></div><div className="money-card"><small>남은 예상 개인 부담</small><strong style={{fontSize:20}}>{amounts(report.personalRemaining)}</strong><p>날짜별 예상 부담 · 결제 미연결</p></div><div className="money-card"><small>개인 실제 + 남은 예상</small><strong style={{fontSize:20}}>{amounts(report.personalForecast)}</strong><p>미확인 개인 금액은 합산 제외</p></div></div><p className="note">실제 개인 금액 미확인 {report.unknownPersonalActual}건 · 남은 예상 부담 미확인 {report.unknownPersonalRemaining}회. 결제와 연결한 청구는 내 부담액을 모르는 경우에도 예상에 다시 넣지 않습니다. 통화별로 합산하며 환산하지 않습니다.</p></details>
 </section>;
}
