import {money,activeTerms,type Contract} from '@/lib/billing';
import type {ComparisonInput} from '@/lib/dated-comparison';
const answer={yes:'확인·충족',no:'미충족',unknown:'미확인'};
const cycles={monthly:'매월',quarterly:'3개월마다',annual:'매년',custom:'개월 간격 지정',manual:'한 번'};
export default function ComparisonConditions({conditions:v,contracts}:{conditions:ComparisonInput;contracts:Contract[]}){const c=v.candidate;return <div className="saved-conditions"><dl>
 <dt>이용 전환일</dt><dd>{v.switchDate}</dd><dt>변경 후 기존 청구</dt><dd>{{stop:'전환일부터 추가 청구 없음',through:'마지막 청구일까지 유지',keep:'기존 조건 유지',unknown:'미확인'}[v.oldBilling]}{v.oldBilling==='through'?' · '+v.oldLastChargeDate:''}</dd><dt>기존 이용 종료</dt><dd>{v.oldAccess==='ends'?v.oldAccessUntil:v.oldAccess==='continues'?'비교 종료일까지 계속 이용':'미확인'}</dd>
 <dt>새 요금제</dt><dd>{c.name} · {c.amount==null?'금액 미확인':money(c.amount,c.currency)} · {cycles[c.cycle]}{c.cycle==='custom'?' '+c.cycleMonths+'개월':''}</dd><dt>새 첫 청구·기준일</dt><dd>{c.nextDate||'미확인'} · 기준 {c.anchorDate||c.nextDate||'미확인'}</dd><dt>요금 기준</dt><dd>{{total:'전체 계약',perSeat:'좌석당',unknown:'미확인'}[c.amountBasis]} · 좌석 {c.seats??'미입력'} · {{fixed:'정액',usage:'사용량',hybrid:'기본료 + 사용량'}[c.pricingMode]}</dd><dt>세금</dt><dd>{{included:'포함',excluded:'별도',unknown:'미확인'}[c.taxStatus]}{c.taxStatus==='excluded'?' · '+(c.taxAmount==null?'금액 미확인':money(c.taxAmount,c.currency)):''}</dd>
 <dt>정상가 적용</dt><dd>{c.priceChangesAt?c.priceChangesAt+' · '+(c.renewalAmount==null?'금액 미확인':money(c.renewalAmount,c.currency)):'변경 일정 미입력'}</dd><dt>요금 근거</dt><dd>{v.quoteSource||'미확인'} · {v.quoteCheckedAt||'확인일 미입력'}</dd><dt>기능·사용량·전체 이용 기간</dt><dd>유지안 {answer[v.criteria.keepFit]} · 변경안 {answer[v.criteria.changeFit]}</dd><dt>할인 자격·변경 의향</dt><dd>{answer[v.criteria.eligibility]} · {answer[v.criteria.changeWilling]}</dd><dt>한 번에 준비 가능</dt><dd>{Object.entries(v.criteria.budgets).map(([c,n])=><span key={c}>{c} {n==null?'미확인':money(n,c)} · </span>)}</dd><dt>추가 비용·환불 검토</dt><dd>{v.extrasConfirmed?'확인함':'미확인'}</dd>
 </dl>{v.adjustments.map((a,i)=><p className="note" key={a.id}>추가 {i+1} · {a.scenario==='keep'?'유지안':'변경안'} · {{fee:'수수료',refund:'환불',proration:'일할 추가 정산'}[a.type]} · {a.recordedPaymentId?'원장 환불 연결':`${a.date||'날짜 미확인'} · ${a.amount==null?'금액 미확인':money(a.amount,a.currency)} · ${a.confirmed?'확인함':'미확인'} · ${a.source||'근거 미입력'}`}</p>)}
 <h4>저장 당시 기존 계약 이력</h4>{contracts[0]?.termsHistory?activeTerms(contracts[0].termsHistory).map(t=><p className="note" key={t.id}>{t.effectiveFrom}부터 · {t.terms.plan||'요금제 미입력'} · {t.terms.amount==null?'금액 미확인':money(t.terms.amount,t.terms.currency)} / {cycles[t.terms.cycle]} · 다음 청구 {t.terms.nextDate||'미확인'} · {t.reason}</p>):<p className="note">조건 이력 미확인</p>}</div>;}
