'use client';
import {money} from '@/lib/billing';
import type {ComparisonResult,CostEvent} from '@/lib/dated-comparison';
function amounts(values:Record<string,number>,currencies:string[]){return currencies.length?currencies.map(c=><strong key={c}>{money(values[c]||0,c)}</strong>):<strong>청구 없음</strong>;}
function Events({events,label}:{events:CostEvent[];label:string}){return events.length?<div className="comparison-table" tabIndex={0} role="region" aria-label={label}><table className="data-table"><thead><tr><th scope="col">날짜</th><th scope="col">구분</th><th scope="col">금액</th></tr></thead><tbody>{events.map((e,i)=><tr key={i}><td>{e.date}</td><td>{e.label}</td><td>{e.amount==null?'미확인':money(e.amount,e.currency)}</td></tr>)}</tbody></table></div>:<p className="note">이 기간에 포함되는 기록·예정 청구가 없습니다.</p>;}
export default function CostComparisonResult({result:r}:{result:ComparisonResult}){return <section className="comparison-result" aria-label="비교 결과">
 <div className="section-heading"><div><h3>같은 기간의 지출</h3><p>{r.from} – {r.until} · 계산 기준 {r.asOf}</p></div><span className="badge gray">계약 총액 기준</span></div>
 <div className="money-grid">{(['keep','change'] as const).map(key=>{const s=r[key];return <div className="money-card" key={key}><small>{key==='keep'?'유지안':'변경안'} · {s.complete?'기록 + 예정 지출':'확인된 금액만'}</small>{amounts(s.total,r.currencies)}<p>조건 {s.feasible===true?'충족':s.feasible===false?'미충족':'확인 필요'}{s.cashOver?' · 준비 금액 초과':s.cashUnknown?' · 준비 금액 미확인':''}</p><div className="line-section"><h4>한 번에 필요한 최대 금액</h4>{Object.entries(s.peak).length?Object.entries(s.peak).map(([c,p])=><p key={c}>{p.date} · {money(p.amount,c)}</p>):<p>확인된 추가 청구 없음</p>}<p>같은 날의 청구·수수료를 합산합니다. 환불은 차감하지 않습니다.</p></div>{s.coverageConflict&&<p className="note warning">기존 계약의 이용 종료일이 비교 종료일보다 빠릅니다. 전체 기간을 이용할 수 있는지 조건을 확인하세요.</p>}{s.issues.length>0&&<ul className="comparison-issues">{s.issues.map(i=><li key={i}>{i}</li>)}</ul>}</div>;})}</div>
 <div className="note" style={{marginTop:16}}><strong>{r.cheaper?r.cheaper==='equal'?'두 안의 기간 내 총액이 같습니다.':`${r.cheaper==='keep'?'유지안':'변경안'}이 ${money(Math.abs(r.difference[r.currencies[0]]),r.currencies[0])} 적습니다.`:'최종 절약액 판단 보류'}</strong><p>{r.recommendation?`입력한 기능·이용 기간·할인·준비 금액 조건에서는 ${r.recommendation==='keep'?'유지안':'변경안'}을 선택할 수 있습니다.`:'금액과 실행 조건을 모두 확인하면 선택 가능한 안을 표시합니다.'}</p>{r.currencies.length>1&&<p>통화별 합계입니다. 환율을 가정해 서로 차감하지 않습니다.</p>}{r.preparationOutsidePeriod&&<p>비교 기간 전에 필요한 청구가 있습니다. 아래 금액을 확인하거나 시작일을 앞당겨 전체 전환 비용을 비교하세요.</p>}</div>
 <p className="note" style={{marginTop:14}}>기존·신규 이용 겹침: {r.overlap?r.overlap.days>0?`${r.overlap.from} – ${r.overlap.until} (${r.overlap.days}일)`:'없음':'기존 이용 종료일 미확인'}. 겹친 일수만으로 비용이나 환불을 만들지 않습니다. 기록된 결제·환불은 두 안에 공통으로 한 번씩 반영됩니다.</p>
 <details className="comparison-details"><summary>날짜별 금액 확인</summary><div className="grid-2">{(['keep','change'] as const).map(key=><div key={key}><h4>{key==='keep'?'유지안':'변경안'}</h4>{r[key].preparation.length>0&&<><p className="note warning">비교 기간 전 준비할 금액 · 기간 합계에서는 제외</p><Events events={r[key].preparation} label={(key==='keep'?'유지안':'변경안')+' 기간 전 준비 금액'}/></>}<Events events={r[key].events} label={(key==='keep'?'유지안':'변경안')+' 날짜별 금액'}/></div>)}</div></details>
 </section>;}
