'use client';
import {useState,useCallback} from 'react';
import {searchCatalog,categories,kindLabels} from '@/lib/catalog';
import {ToolCard} from './ToolUI';
import {useToolSearchMCP} from './useToolSearchMCP';
import Link from '@/components/Link';
import {Search,ArrowRight} from './Icons';
import SearchMeaning from './SearchMeaning';
export default function Explore({initialQuery='',initialCategory='all',isSearch=false}:{initialQuery?:string;initialCategory?:string;isSearch?:boolean}){const [q,setQ]=useState(initialQuery),[category,setCategory]=useState(initialCategory),[kind,setKind]=useState('all'),[free,setFree]=useState(false),[korean,setKorean]=useState(false);useToolSearchMCP(useCallback((v)=>{setQ(v.q);setCategory(v.category);setKind(v.kind);setFree(v.free);setKorean(v.korean);},[]));const results=searchCatalog(q,{category,kind,free,korean});return <><div className="page-title"><div><span className="eyebrow">Explore tools</span><h1>{isSearch?'필요한 도구 찾기':'도구 탐색'}</h1><p>기능과 이용 조건을 확인하고, 최대 3개를 비교하세요.</p></div><div className="actions"><Link className="text-link" href="/recommend">업무별 추천<ArrowRight size={14}/></Link><Link className="text-link" href="/ranking">참여 랭킹<ArrowRight size={14}/></Link><Link className="text-link" href="/resources">유용한 사이트<ArrowRight size={14}/></Link></div></div><div className="search-bar"><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} aria-label="도구 이름 또는 목적 검색" placeholder="예: 보고서 작성, Cursor, 자동화"/>{q&&<button className="button ghost small" onClick={()=>setQ('')}>지우기</button>}</div><div className="filters"><select aria-label="업무 분야" value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries(categories).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><select aria-label="도구 유형" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">모든 유형</option>{Object.entries(kindLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><label className="check-label"><input type="checkbox" checked={free} onChange={e=>setFree(e.target.checked)}/>무료 플랜 있음</label><label className="check-label"><input type="checkbox" checked={korean} onChange={e=>setKorean(e.target.checked)}/>한국어 지원 확인</label></div><SearchMeaning query={q}/><div className="results-meta"><span role="status">{results.length}개 결과{q&&' · “'+q+'”'}</span><span>{q?'입력한 목적과의 관련도순':'이름순'} · 평점순 아님</span></div>{results.length?<div className="grid-3">{results.map(t=><ToolCard key={t.id} tool={t}/>)}</div>:<div className="empty"><h3>조건에 맞는 도구가 없습니다.</h3><p>검색어를 짧게 바꾸거나 필터를 줄여보세요. 확인되지 않은 기능을 지원으로 간주하지 않습니다.</p><button className="button secondary" onClick={()=>{setQ('');setCategory('all');setKind('all');setFree(false);setKorean(false);}}>조건 초기화<ArrowRight size={16}/></button></div>}</>;}
