'use client';
import {useEffect,useState} from 'react';
import Link from './Link';
import {api} from './Provider';
import {Search,ArrowRight} from './Icons';
type Results={results:{id:string;type:string;title:string;summary:string;href:string;meta:string}[];counts:Record<string,number>;total:number;partial:boolean};
const labels:Record<string,string>={all:'전체',tool:'도구',guide:'가이드',news:'소식·업데이트',event:'행사',community:'커뮤니티',comparison:'비교 콘텐츠'};
export default function GlobalSearch({initialQuery='',initialType='all'}:{initialQuery?:string;initialType?:string}){
 const [q,setQ]=useState(initialQuery),[submitted,setSubmitted]=useState(initialQuery),[type,setType]=useState(labels[initialType]?initialType:'all'),[data,setData]=useState<Results|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let alive=true;setData(null);setError('');if(!submitted){setLoading(false);return;}setLoading(true);api<Results>('/api/search?q='+encodeURIComponent(submitted)+'&type='+type).then(d=>{if(alive)setData(d);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[submitted,type,retry]);
 function update(query:string,t:string){setSubmitted(query);setType(t);history.replaceState(null,'','/search?q='+encodeURIComponent(query)+'&type='+t);}
 return <><div className="page-title"><div><span className="eyebrow">Search AIs</span><h1>전체 검색</h1><p>도구와 활용 정보, 공개된 경험을 함께 찾아보세요.</p></div><Link className="text-link" href="/explore">기능 조건으로 도구 찾기<ArrowRight size={15}/></Link></div><form className="search-bar" role="search" onSubmit={e=>{e.preventDefault();update(q.trim(),type);}}><Search size={20}/><input maxLength={160} value={q} onChange={e=>setQ(e.target.value)} aria-label="전체 콘텐츠 검색" placeholder="도구, 업무, 가이드 또는 행사 검색"/><button className="button primary small" type="submit">검색</button></form><div className="filters" aria-label="검색 유형">{Object.entries(labels).map(([id,label])=><button key={id} className={'button small '+(type===id?'primary':'ghost')} aria-pressed={type===id} onClick={()=>update(submitted,id)}>{label}{data?' '+(id==='all'?data.total:data.counts[id]||0):''}</button>)}</div>{error&&<p className="error" role="alert">{error}<button className="button ghost small" onClick={()=>setRetry(v=>v+1)}>다시 불러오기</button></p>}{loading?<p className="loading" role="status">검색 결과를 불러오고 있습니다.</p>:!submitted?<div className="empty"><h3>어떤 정보가 필요한가요?</h3><p>예: 보고서 작성, ChatGPT, Vercel</p><p className="metadata">개인 도구함과 메모는 공개 검색에 포함되지 않습니다.</p></div>:data&&<>{data.partial&&<p className="note warning" role="status">커뮤니티 검색을 불러오지 못했습니다. 다른 콘텐츠 결과를 표시합니다.<button className="button ghost small" onClick={()=>setRetry(v=>v+1)}>다시 시도</button></p>}<div className="results-meta" role="status"><span>“{submitted}” · {data.results.length}개 결과</span><span>관련도순</span></div>{data.results.length?Object.entries(labels).filter(([id])=>id!=='all').map(([id,label])=>{const items=data.results.filter(r=>r.type===id);return items.length?<section className="line-section" key={id}><h2>{label} <span className="metadata">{items.length}개</span></h2>{items.map(r=><article className="record-row" key={r.id}><div><span className="metadata">{r.meta}</span><h3><Link href={r.href}>{r.title}</Link></h3><p>{r.summary}</p></div><Link className="text-link" href={r.href} aria-label={r.title+' 보기'}><ArrowRight size={18}/></Link></article>)}</section>:null;}):<div className="empty"><h3>검색 결과가 없습니다.</h3><p>{type==='comparison'?'등록된 비교 콘텐츠가 없습니다. 도구 탐색에서 직접 비교할 수 있습니다.':'검색어를 줄이거나 다른 유형을 선택해보세요.'}</p><Link className="button secondary" href="/explore">도구 탐색</Link></div>}</>}</>;
}
