'use client';
import {useEffect,useState} from 'react';
import Link from '@/components/Link';
import {api,useApp} from './Provider';
import {dateLabel} from '@/lib/content';
import {ArrowRight,RefreshCw,Check} from './Icons';
import EmailDeliveryStatus from './EmailDeliveryStatus';
import type {EmailStatus} from '@/lib/email-status';
type Notice={id:string;source_key:string;title:string;body:string;href:string;read:number;created_at:string;updated_at:string;status:string;email_reason:string};
export default function Notifications({onChanged}:{onChanged?:()=>void}){const {toast}=useApp(),[items,setItems]=useState<Notice[]>([]),[email,setEmail]=useState<EmailStatus|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);async function refresh(generate=false){setLoading(true);setError('');try{if(generate)await api('/api/notifications',{method:'POST',body:JSON.stringify({action:'refresh'})});const d=await api<{notifications:Notice[];email:EmailStatus}>('/api/notifications');setItems(d.notifications);setEmail(d.email);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}useEffect(()=>{void refresh(true);},[]);async function read(id:string){try{await api('/api/notifications',{method:'POST',body:JSON.stringify({action:'read',id,expectedSourceKey:items.find(n=>n.id===id)?.source_key})});setItems(old=>old.map(i=>i.id===id?{...i,read:1}:i));}catch(e){toast((e as Error).message);}}async function hide(id:string){try{await api('/api/notifications',{method:'POST',body:JSON.stringify({action:'hide',id})});onChanged?.();toast('이 주제의 알림을 숨겼습니다. 설정에서 다시 받을 수 있습니다.');await refresh();}catch(e){toast((e as Error).message);}}return <><div className="section-heading"><h2>알림</h2><button className="button ghost small" disabled={loading} onClick={()=>refresh(true)}><RefreshCw size={14}/>새로 확인</button></div>{error&&<p className="error" role="alert">{error}</p>}{email&&<EmailDeliveryStatus status={email}/>}
{loading?<p className="loading">새 알림을 확인하고 있습니다.</p>:items.length?<div className="stack">{items.map(n=><article key={n.id} className={'notice-row '+(!n.read?'unread':'')}><span className="metadata">{{corrected:'조건 정정',updated:'내용 변경',withdrawn:'공식 안내 철회',expired:'마감·종료'}[n.status]||'관심 소식'}</span><h3>{n.title}</h3><p>{n.body}</p>{n.email_reason&&<p className="note" style={{marginTop:12}}>확인할 조건: {n.email_reason}</p>}<span className="metadata" style={{marginTop:8}}>{dateLabel(n.created_at)}</span><div className="actions" style={{marginTop:13}}><Link className="text-link" href={n.href} onClick={()=>read(n.id)}>내용 확인<ArrowRight size={14}/></Link>{!n.read&&<button className="button ghost small" onClick={()=>read(n.id)}><Check size={13}/>읽음 표시</button>}<button className="button ghost small" onClick={()=>hide(n.id)}>이 주제 관심 없음</button></div></article>)}</div>:<div className="empty"><h3>새 알림이 없습니다.</h3><p>설정에서 관심 서비스를 선택하면 업데이트와 혜택을 확인할 수 있습니다. 등록한 다음 결제일이 7일 이내로 다가오면 알림이 표시됩니다.</p><a className="text-link" href="/my?tab=settings">관심 서비스 설정<ArrowRight size={14}/></a></div>}<p className="note" style={{marginTop:22}}>알림 화면을 열 때 새 정보를 확인합니다. 확인일만 바뀐 소식은 다시 보내지 않습니다. 혜택의 중요한 변경은 원래 카드에 반영하며, 필요한 정정은 수신 설정에 따라 안내합니다.</p></>;}
