'use client';
import {useEffect,useRef,useState} from 'react';
import type {Metric} from 'web-vitals';

type Reading={value:number;rating:string;id:string;navigationType:string};
type Snapshot={elapsedMs:number;initialVisibility:string;visibilityChanges:number;supportedEntries:string[];rawLayout:{supported:boolean;count:number;sessionMax:number};readings:Record<string,Reading>;initialDocumentPath:string;path:string;capturedAt:string;visibility:string;framed:boolean;viewport:string;documentWidth:number;scrollWidth:number;observerStartedAt:number;navigation:{encodedBytes:number;transferBytes:number;responseEndMs:number;domInteractiveMs:number;domCompleteMs:number;type:string}|null;resources:{count:number;encodedBytes:number;transferBytes:number;unknownSizes:number;scriptEncodedBytes:number};longTasks:{supported:boolean;count:number;totalMs:number;over50Ms:number;maxMs:number};images:{alt:string;loaded:boolean;source:string}[]};

export default function PerformanceDiagnostics(){
 const [enabled,setEnabled]=useState(false),[open,setOpen]=useState(false),[readings,setReadings]=useState<Record<string,Reading>>({}),[snapshot,setSnapshot]=useState<Snapshot|null>(null),[error,setError]=useState(''),[loadSnapshot,setLoadSnapshot]=useState<Snapshot|null>(null);
 const flushObservers=useRef(()=>{});
 const initialPath=useRef(''),initialVisibility=useRef(''),visibilityChanges=useRef(0),start=useRef(0),metricValues=useRef<Record<string,Reading>>({}),tasks=useRef({supported:false,count:0,totalMs:0,over50Ms:0,maxMs:0}),shifts=useRef({supported:false,count:0,sessionMax:0,sessionStart:0,last:0,value:0});
 useEffect(()=>{
  if(new URLSearchParams(location.search).get('diagnostics')!=='1')return;
  setEnabled(true);initialPath.current=location.pathname;initialVisibility.current=document.visibilityState;start.current=performance.now();let active=true;let observer:PerformanceObserver|undefined;let shiftObserver:PerformanceObserver|undefined;const visibility=()=>{visibilityChanges.current++;};document.addEventListener('visibilitychange',visibility);const timer=setTimeout(()=>setLoadSnapshot(readSnapshot()),Math.max(0,10000-performance.now()));
  try{if(PerformanceObserver.supportedEntryTypes.includes('longtask')){tasks.current.supported=true;const consumeTasks=(entries:PerformanceEntry[])=>{for(const entry of entries){tasks.current.count++;tasks.current.maxMs=Math.max(tasks.current.maxMs,entry.duration);tasks.current.totalMs+=entry.duration;tasks.current.over50Ms+=Math.max(0,entry.duration-50);}};observer=new PerformanceObserver(list=>consumeTasks(list.getEntries()));flushObservers.current=()=>consumeTasks(observer?.takeRecords()||[]);observer.observe({type:'longtask',buffered:true});}}catch{}
  try{if(PerformanceObserver.supportedEntryTypes.includes('layout-shift')){shifts.current.supported=true;const consumeShifts=(entries:PerformanceEntry[])=>{for(const raw of entries){const entry=raw as PerformanceEntry&{hadRecentInput:boolean;value:number};if(entry.hadRecentInput)continue;const value=shifts.current;value.count++;if(value.value>0&&entry.startTime-value.last<1000&&entry.startTime-value.sessionStart<5000)value.value+=entry.value;else{value.sessionStart=entry.startTime;value.value=entry.value;}value.last=entry.startTime;value.sessionMax=Math.max(value.sessionMax,value.value);}};shiftObserver=new PerformanceObserver(list=>consumeShifts(list.getEntries()));const flushTasks=flushObservers.current;flushObservers.current=()=>{flushTasks();consumeShifts(shiftObserver?.takeRecords()||[]);};shiftObserver.observe({type:'layout-shift',buffered:true});}}catch{}
  import('web-vitals').then(({onCLS,onFCP,onINP,onLCP,onTTFB})=>{if(!active)return;const report=(metric:Metric)=>{if(active){metricValues.current={...metricValues.current,[metric.name]:{value:metric.value,rating:metric.rating,id:metric.id,navigationType:metric.navigationType}};setReadings(metricValues.current);}};onCLS(report,{reportAllChanges:true});onLCP(report,{reportAllChanges:true});onINP(report,{reportAllChanges:true,durationThreshold:16});onFCP(report);onTTFB(report);}).catch(()=>{if(active)setError('성능 측정 모듈을 불러오지 못했습니다.');});
  return()=>{active=false;observer?.disconnect();shiftObserver?.disconnect();clearTimeout(timer);document.removeEventListener('visibilitychange',visibility);};
 },[]);
 function readSnapshot():Snapshot{
  flushObservers.current();
  const resources=performance.getEntriesByType('resource') as PerformanceResourceTiming[];
  const navigation=performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming|undefined;
  return {elapsedMs:Math.round(performance.now()),initialVisibility:initialVisibility.current,visibilityChanges:visibilityChanges.current,supportedEntries:[...PerformanceObserver.supportedEntryTypes],rawLayout:{supported:shifts.current.supported,count:shifts.current.count,sessionMax:shifts.current.sessionMax},readings:structuredClone(metricValues.current),initialDocumentPath:initialPath.current,path:location.pathname,capturedAt:new Date().toISOString(),visibility:document.visibilityState,framed:window.top!==window,viewport:innerWidth+' × '+innerHeight,documentWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,observerStartedAt:Math.round(start.current),navigation:navigation?{encodedBytes:navigation.encodedBodySize,transferBytes:navigation.transferSize,responseEndMs:navigation.responseEnd,domInteractiveMs:navigation.domInteractive,domCompleteMs:navigation.domComplete,type:navigation.type}:null,resources:{count:resources.length,encodedBytes:resources.reduce((n,r)=>n+r.encodedBodySize,0),transferBytes:resources.reduce((n,r)=>n+r.transferSize,0),unknownSizes:resources.filter(r=>r.encodedBodySize===0).length,scriptEncodedBytes:resources.filter(r=>r.initiatorType==='script'||/\.m?js(?:[?]|$)/.test(r.name)).reduce((n,r)=>n+r.encodedBodySize,0)},longTasks:{...tasks.current,totalMs:Math.round(tasks.current.totalMs),over50Ms:Math.round(tasks.current.over50Ms)},images:Array.from(document.images).map(i=>({alt:i.alt,loaded:i.complete&&i.naturalWidth>0,source:i.getAttribute('src')?.split('?')[0]||''}))};
 }
 function capture(){setSnapshot(readSnapshot());setOpen(true);}
 if(!enabled)return null;
 return <aside aria-label="성능 진단" style={{position:'fixed',right:12,bottom:12,zIndex:120,width:open?'min(560px, calc(100vw - 24px))':'auto',maxHeight:'75vh',overflow:'auto',background:'var(--paper)',border:'1px solid var(--line)',borderRadius:10,padding:12,boxShadow:'0 4px 20px #15254b22'}}>
  <div className="actions"><button className="button secondary small" onClick={capture}>현재 성능 기록</button>{open&&<button className="button ghost small" onClick={()=>setOpen(false)}>진단 접기</button>}</div>
  {open&&<div style={{marginTop:14,fontSize:12}}><h2 style={{fontSize:16}}>이 페이지의 관측값</h2><p className="note">진단을 켠 단일 방문의 측정입니다. 실제 사용자 전체의 백분위나 인증 결과가 아닙니다. 측정값은 서버로 전송·저장하지 않습니다.</p>{error&&<p role="alert">{error}</p>}
   <table className="data-table"><thead><tr><th>지표</th><th>관측값</th><th>라이브러리 판정</th></tr></thead><tbody>{['TTFB','FCP','LCP','INP','CLS'].map(name=>{const reading=(snapshot?.readings||readings)[name];return <tr key={name}><td>{name}</td><td>{reading?name==='CLS'?reading.value.toFixed(4):Math.round(reading.value)+' ms':'미관측'}</td><td>{reading?.rating||'—'}</td></tr>;})}</tbody></table>
   <p className="note">기록 버튼을 눌렀을 때의 값을 고정합니다. 같은 문서에서 경로만 바뀌어도 지표는 누적되므로 화면별 측정은 새로 로드하세요. INP는 이 문서에서 수행한 상호작용이 필요합니다. LCP·CLS는 관측 중 갱신될 수 있습니다. 하위 프레임 값은 호스팅 화면 전체를 대표하지 않습니다. 늦게 시작한 관측과 브라우저 지원 범위 때문에 누락이 있을 수 있습니다.</p>
   {snapshot&&<><dl><dt>범위·시각</dt><dd>{snapshot.initialDocumentPath} → {snapshot.path} · {snapshot.capturedAt}</dd><dt>프레임·가시성</dt><dd>{snapshot.framed?'하위 프레임':'최상위 문서'} · {snapshot.visibility}</dd><dt>화면·문서·스크롤 폭</dt><dd>{snapshot.viewport} · {snapshot.documentWidth} / {snapshot.scrollWidth}px</dd><dt>관측기 시작</dt><dd>문서 시작 후 {snapshot.observerStartedAt}ms · 지원되는 이전 항목 포함 · 캡처 {snapshot.elapsedMs}ms</dd><dt>문서 응답</dt><dd>{snapshot.navigation?`압축 본문 ${snapshot.navigation.encodedBytes}B · 전송 ${snapshot.navigation.transferBytes}B`:'미관측'}</dd><dt>하위 리소스</dt><dd>{snapshot.resources.count}개 · 확인된 압축 본문 {snapshot.resources.encodedBytes}B · 전송 {snapshot.resources.transferBytes}B · 크기 0/미제공 {snapshot.resources.unknownSizes}개</dd><dt>긴 작업</dt><dd>{snapshot.longTasks.supported?`${snapshot.longTasks.count}회 · 합계 ${snapshot.longTasks.totalMs}ms · 최대 ${Math.round(snapshot.longTasks.maxMs)}ms · 각 50ms 초과분 합계 ${snapshot.longTasks.over50Ms}ms`:'이 브라우저에서 미지원'}</dd></dl><p className="note">리소스의 0은 캐시·빈 응답·크기 미제공을 포함할 수 있습니다. 전송 값은 브라우저가 보고한 헤더 추정·캐시 조건을 포함하며 실제 전체 네트워크 비용으로 확정하지 않습니다. 긴 작업 초과분은 Lighthouse TBT와 다른 관측 합계입니다.</p><details><summary>이미지 로딩 {snapshot.images.filter(i=>i.loaded).length}/{snapshot.images.length}</summary><ul>{snapshot.images.map((i,n)=><li key={n}>{i.loaded?'확인':'미완료'} · {i.alt||'대체 텍스트 없음'} · {i.source}</li>)}</ul></details><p className="note">초기 관측은 문서 시작 10초를 목표로 자동 기록합니다. 초기화나 작업 지연이 있으면 더 늦게 기록되며 JSON의 elapsedMs가 실제 관측시간입니다. 하위 프레임에서 FCP·CLS가 제공되지 않으면 미관측으로 남습니다. rawLayout은 최근 입력을 제외한 문서 내 이동의 별도 세션 최대값이며 전체 페이지 CLS를 뜻하지 않습니다.</p><details><summary>10초 목표 자동 기록 JSON · 실제 관측시간 기준</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontSize:10}}>{loadSnapshot?JSON.stringify(loadSnapshot,null,2):'아직 관측 중입니다.'}</pre></details><details><summary>측정 기록 JSON</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontSize:10}}>{JSON.stringify(snapshot,null,2)}</pre></details></>}
  </div>}
 </aside>;
}
