'use client';
import promotions from '@/data/promotions.json';
import {eligibilityFingerprint,featureLabels,type Promotion} from '@/lib/promotion-facts';
export default function PromotionPreferences({value:v,onChange}:{value:Record<string,any>;onChange:(fields:Record<string,any>)=>void}){
 return <details style={{marginBottom:24}}><summary>혜택 조건 · 자격과 예산</summary><p className="note">조건이 불확실한 혜택은 앱에 확인할 항목을 표시하고 이메일은 보류합니다. 이미 안내를 시도한 혜택의 중요한 정정은 현재 수신 설정에 따라 알립니다.</p>
 <div className="grid-3" style={{gap:16,margin:'20px 0'}}><label className="field">월요금 상한<input type="number" min="0" step="0.01" placeholder="제한 없음" value={v.maxPrice??''} onChange={e=>onChange({maxPrice:e.target.value===''?null:Number(e.target.value)})}/><small>혜택 기간과 갱신 후 모두 적용합니다. 세금 포함 가격이 확인되어야 합니다.</small></label><label className="field">가격 통화<select value={v.currency||'KRW'} onChange={e=>onChange({currency:e.target.value})}><option value="KRW">KRW · 원</option><option value="USD">USD · 달러</option><option value="EUR">EUR · 유로</option><option value="JPY">JPY · 엔</option></select><small>다른 통화는 자동 환산하지 않습니다.</small></label><label className="field">최소 혜택 기간 · 개월<input type="number" min="1" max="120" step="1" placeholder="제한 없음" value={v.minBenefitMonths??''} onChange={e=>onChange({minBenefitMonths:e.target.value===''?null:Number(e.target.value)})}/></label></div>
 <fieldset style={{border:0,padding:0,margin:'0 0 24px'}}><legend style={{marginBottom:12}}>반드시 필요한 기능</legend><div className="grid-2" style={{gap:12}}>{Object.entries(featureLabels).map(([id,label])=><label key={id} className="check-label"><input type="checkbox" checked={(v.neededFeatures||[]).includes(id)} onChange={e=>onChange({neededFeatures:e.target.checked?[...(v.neededFeatures||[]),id]:(v.neededFeatures||[]).filter((x:string)=>x!==id)})}/>{label}</label>)}</div><p className="metadata" style={{marginTop:12}}>행사에 적용되는 요금제의 지원 근거를 확인합니다. 서비스의 일반 기능만으로 지원을 판단하지 않습니다.</p></fieldset>
 {(promotions as Promotion[]).map(p=>{const token=eligibilityFingerprint(p),stale=v.promotionEligibility?.[p.id]==='eligible'&&v.promotionEligibilityVersions?.[p.id]!==token;return <label className="field" key={p.id}>{p.name}<small>{p.region} · <a href={p.url} target="_blank" rel="noreferrer">현재 공식 자격 조건 확인 ↗</a></small>{stale&&<small className="error">현재 조건으로 자격을 다시 확인해주세요.</small>}<select value={stale?'unknown':v.promotionEligibility?.[p.id]||'unknown'} onChange={e=>onChange({promotionEligibility:{...v.promotionEligibility,[p.id]:e.target.value},promotionEligibilityVersions:{...v.promotionEligibilityVersions,[p.id]:e.target.value==='eligible'?token:''}})}><option value="unknown">자격 미확인</option><option value="ineligible">해당하지 않음</option><option value="eligible">현재 지역·학생·계정·결제 조건을 모두 확인함</option></select></label>;})}</details>;
}
