'use client';
import {useEffect,useRef,useState} from 'react';
import Link from '@/components/Link';
import {Plus,Save,Trash2} from 'lucide-react';
import {api,useApp} from './Provider';
import type {PrivateRecord} from './RecordForm';
import Modal from './Modal';
import SimpleSavings from './SimpleSavings';
import CostComparisonResult from './CostComparisonResult';
import ComparisonConditions from './ComparisonConditions';
import {billingIdentity,currencies,fromMinor,horizonEndDate,money,toMinor,today,type Contract,type Payment} from '@/lib/billing';
import {datedComparison,type ComparisonInput,type ComparisonResult} from '@/lib/dated-comparison';
const decisions={consider:'검토 중',stay:'유지',change:'변경 예정',defer:'보류',notInterested:'관심 없음'};
const initial=():ComparisonInput=>({from:today(),until:horizonEndDate(today(),12),switchDate:today(),oldBilling:'unknown',oldLastChargeDate:null,oldAccess:'unknown',oldAccessUntil:null,candidate:{name:'',amount:null,currency:'KRW',cycle:'monthly',nextDate:null,anchorDate:null,amountBasis:'total',seats:null,taxStatus:'unknown',taxAmount:null,pricingMode:'fixed',priceChangesAt:null,renewalAmount:null},adjustments:[],extrasConfirmed:false,quoteSource:'',quoteCheckedAt:null,criteria:{keepFit:'unknown',changeFit:'unknown',eligibility:'unknown',changeWilling:'unknown',budgets:{}}});
const displayed=(n:number|null|undefined,c:string)=>n==null?'':String(fromMinor(n,c));
type Preview={result:ComparisonResult;conditions:ComparisonInput;subscriptionId:string;expectedRevision:number;historyId:string};
export default function Savings({records,onSaved}:{records:PrivateRecord[];onSaved:()=>void}){
 const {toast}=useApp(),form=useRef<HTMLFormElement>(null),[seed,setSeed]=useState(initial),[formKey,setFormKey]=useState(0),[selectedId,setSelectedId]=useState(''),[candidateCurrency,setCurrency]=useState('KRW'),[cycle,setCycle]=useState('monthly'),[oldBilling,setOldBilling]=useState('unknown'),[oldAccess,setOldAccess]=useState('unknown'),[adjustments,setAdjustments]=useState<ComparisonInput['adjustments']>([]),[preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[opened,setOpened]=useState<string|null>(null),[deleting,setDeleting]=useState<PrivateRecord|null>(null);
 const subs=records.filter(r=>r.kind==='subscription'),selected=subs.find(s=>s.id===(selectedId||subs[0]?.id)),identity=selected?billingIdentity({id:selected.id,bundleId:selected.payload.bundleId}):'',members=subs.filter(s=>billingIdentity({id:s.id,bundleId:s.payload.bundleId})===identity),payments=records.filter(r=>r.kind==='payment'&&members.some(s=>s.id===r.payload.subscriptionId)),saved=records.filter(r=>r.kind==='costComparison');
 useEffect(()=>{if(!preview)return;const current=records.find(r=>r.kind==='subscription'&&r.id===preview.subscriptionId);if(!current||current.payload.historyId!==preview.historyId||current.payload.termsHistory?.revision!==preview.expectedRevision){setPreview(null);setError('계약·결제 기록이 갱신되었습니다. 최신 조건으로 다시 비교해주세요.');}},[records,preview]);
 const clear=()=>{setPreview(null);setError('');};
 function read():ComparisonInput{const d=new FormData(form.current!),value=(key:string)=>String(d.get(key)||''),date=(key:string)=>value(key)||null,amount=(key:string,c=candidateCurrency)=>value(key).trim()===''?null:toMinor(value(key),c),a=(key:string)=>value(key) as 'yes'|'no'|'unknown';return {from:value('from'),until:value('until'),switchDate:value('switchDate'),oldBilling:oldBilling as ComparisonInput['oldBilling'],oldLastChargeDate:date('oldLastChargeDate'),oldAccess:oldAccess as ComparisonInput['oldAccess'],oldAccessUntil:date('oldAccessUntil'),candidate:{name:value('name'),amount:amount('amount'),currency:candidateCurrency as ComparisonInput['candidate']['currency'],cycle:cycle as ComparisonInput['candidate']['cycle'],cycleMonths:value('cycleMonths')?Number(value('cycleMonths')):null,nextDate:date('nextDate'),anchorDate:date('anchorDate'),amountBasis:value('amountBasis') as ComparisonInput['candidate']['amountBasis'],seats:value('seats')?Number(value('seats')):null,taxStatus:value('taxStatus') as ComparisonInput['candidate']['taxStatus'],taxAmount:amount('taxAmount'),pricingMode:value('pricingMode') as ComparisonInput['candidate']['pricingMode'],priceChangesAt:date('priceChangesAt'),renewalAmount:amount('renewalAmount')},adjustments:adjustments.map(ad=>({...ad,date:date(ad.id+'Date'),amount:amount(ad.id+'Amount',ad.currency),source:value(ad.id+'Source'),confirmed:d.has(ad.id+'Confirmed')})),extrasConfirmed:d.has('extrasConfirmed'),quoteSource:value('quoteSource'),quoteCheckedAt:date('quoteCheckedAt'),criteria:{keepFit:a('keepFit'),changeFit:a('changeFit'),eligibility:a('eligibility'),changeWilling:a('changeWilling'),budgets:Object.fromEntries(currencies.map(c=>[c,amount('budget'+c,c)]))}};}
 function calculate(){clear();try{if(!selected)throw new Error('비교할 구독을 선택해주세요.');if(!selected.payload.historyId)throw new Error('구독·결제에서 기존 조건 이력을 먼저 확인·저장해주세요.');const conditions=read(),result=datedComparison(members.map(m=>({...m.payload,id:m.id} as Contract)),payments.map(p=>({...p.payload,id:p.id} as Payment)),conditions);setPreview({result,conditions,subscriptionId:selected.id,expectedRevision:selected.payload.termsHistory?.revision??0,historyId:selected.payload.historyId||''});}catch(e){setError((e as Error).message);}}
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!preview)return;const d=new FormData(event.currentTarget);setBusy(true);setError('');try{await api('/api/cost-comparisons',{method:'POST',body:JSON.stringify({action:'save',conditions:preview.conditions,subscriptionId:preview.subscriptionId,expectedRevision:preview.expectedRevision,historyId:preview.historyId,title:d.get('title'),decision:d.get('decision'),reason:d.get('reason'),outcome:d.get('outcome')})});toast('비교 조건과 결과를 저장했습니다.');setPreview(null);onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function loadSaved(record:PrivateRecord){const v=record.payload.conditions as ComparisonInput;setSeed(v);setSelectedId(record.payload.subscriptionId);setCurrency(v.candidate.currency);setCycle(v.candidate.cycle);setOldBilling(v.oldBilling);setOldAccess(v.oldAccess);setAdjustments(v.adjustments);setFormKey(k=>k+1);clear();form.current?.scrollIntoView({behavior:'smooth',block:'start'});}
 async function annotate(event:React.FormEvent<HTMLFormElement>,record:PrivateRecord){event.preventDefault();const d=new FormData(event.currentTarget);setBusy(true);try{await api('/api/cost-comparisons',{method:'POST',body:JSON.stringify({action:'annotate',id:record.id,decision:d.get('decision'),reason:d.get('reason'),outcome:d.get('outcome')})});toast('선택 이유와 결과를 저장했습니다.');onSaved();}catch(e){toast((e as Error).message);}finally{setBusy(false);}}
 const dateField=(name:string,label:string,value:string|null|undefined,required=false)=><label className="field">{label}<input type="date" name={name} defaultValue={value||''} required={required}/></label>;
 const moneyField=(name:string,label:string,value:number|null|undefined,c=candidateCurrency)=><label className="field">{label} · {c}<input name={name} inputMode="decimal" defaultValue={displayed(value,c)} placeholder="미확인: 빈칸 · 없음: 0"/></label>;
 const answerField=(name:keyof ComparisonInput['criteria'],label:string)=><label className="field">{label}<select name={name} defaultValue={seed.criteria[name] as string}><option value="unknown">미확인</option><option value="yes">충족·확인</option><option value="no">미충족</option></select></label>;
 const noteFields=(p:Record<string,any>={})=><><label className="field">선택 상태<select name="decision" defaultValue={p.decision||'consider'}>{Object.entries(decisions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="field">선택 이유<textarea name="reason" maxLength={1000} defaultValue={p.reason||''} rows={2}/></label><label className="field">사용·변경 결과<textarea name="outcome" maxLength={2000} defaultValue={p.outcome||''} rows={2}/></label></>;
 return <div className="dated-comparison"><div className="section-heading"><div><h2>구독 변경 비교</h2><p>같은 날짜 범위에서 유지안과 변경안의 실제·예정 지출을 확인하세요.</p></div></div>
 {!subs.length?<div className="empty"><h3>비교할 구독을 먼저 등록하세요.</h3><Link className="button secondary" href="/my?tab=subscription">구독·결제 관리</Link></div>:<>
 <form ref={form} key={formKey} className="panel comparison-form" onChange={clear} onSubmit={e=>{e.preventDefault();calculate();}}>
 <div className="form-grid"><label className="field wide">기존 구독<select value={selected?.id||''} onChange={e=>{setSelectedId(e.target.value);clear();}}>{!selected&&<option value="">구독 선택</option>}{subs.map(s=><option key={s.id} value={s.id}>{s.payload.name}{s.payload.bundleId?' · 번들 '+s.payload.bundleId:''}</option>)}</select></label>{dateField('from','비교 시작일',seed.from,true)}{dateField('until','비교 종료일',seed.until,true)}{dateField('switchDate','새 계약 이용 시작·전환일',seed.switchDate,true)}</div>
 {selected&&<p className="note">{selected.payload.name} · {selected.payload.plan||'요금제 미입력'} · 조건 이력 {selected.payload.termsHistory?.versions.length||0}건{members.length>1?` · 번들 구성 ${members.length}개를 한 계약으로 계산`:''}. 연결된 실제 결제는 예정 청구에서 제외합니다. <Link href="/my?tab=subscription">기존 조건 확인</Link></p>}
 <section className="line-section"><h3>새 요금제</h3><div className="form-grid"><label className="field wide">서비스·요금제 이름<input name="name" defaultValue={seed.candidate.name} required maxLength={100}/></label>{moneyField('amount','1회 청구 금액',seed.candidate.amount)}<label className="field">통화<select value={candidateCurrency} onChange={e=>setCurrency(e.target.value)}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label><label className="field">결제 주기<select value={cycle} onChange={e=>setCycle(e.target.value)}><option value="monthly">매월</option><option value="quarterly">3개월마다</option><option value="annual">매년</option><option value="custom">개월 간격 지정</option><option value="manual">한 번만 청구</option></select></label>{cycle==='custom'&&<label className="field">결제 간격 (개월)<input type="number" name="cycleMonths" min={1} max={120} defaultValue={seed.candidate.cycleMonths||''} required/></label>}{dateField('nextDate','새 요금제 첫 청구일',seed.candidate.nextDate)}<label className="field">세금<select name="taxStatus" defaultValue={seed.candidate.taxStatus}><option value="unknown">미확인</option><option value="included">입력 금액에 포함</option><option value="excluded">별도 부과</option></select></label>{moneyField('taxAmount','별도 세금 · 1회 총액',seed.candidate.taxAmount)}</div>
 <details className="comparison-details"><summary>좌석·사용량·할인·청구 기준일</summary><div className="form-grid"><label className="field">금액 기준<select name="amountBasis" defaultValue={seed.candidate.amountBasis}><option value="total">전체 계약</option><option value="perSeat">좌석당</option><option value="unknown">미확인</option></select></label><label className="field">유료 좌석 수<input type="number" name="seats" min={1} max={100000} defaultValue={seed.candidate.seats??''}/></label><label className="field">과금 방식<select name="pricingMode" defaultValue={seed.candidate.pricingMode}><option value="fixed">정액</option><option value="usage">사용량</option><option value="hybrid">기본료 + 사용량</option></select></label>{dateField('anchorDate','결제 주기 기준일 · 빈칸이면 첫 청구일',seed.candidate.anchorDate)}{dateField('priceChangesAt','할인 종료 후 정상가 적용일',seed.candidate.priceChangesAt)}{moneyField('renewalAmount','정상가 · 위 금액 기준과 동일',seed.candidate.renewalAmount)}</div><p className="note">월말·윤년을 반영해 청구합니다. 사용량 추가 요금은 미확인으로 남으며, 일할 금액은 자동 추정하지 않습니다.</p></details>
 <div className="form-grid"><label className="field">요금 출처·확인한 조건<input name="quoteSource" defaultValue={seed.quoteSource} maxLength={500} placeholder="공식 요금 페이지 또는 받은 견적"/></label>{dateField('quoteCheckedAt','요금 확인일',seed.quoteCheckedAt)}</div></section>
 <section className="line-section"><h3>기존 청구와 이용 종료</h3><div className="form-grid"><label className="field">변경 후 기존 계약 청구<select value={oldBilling} onChange={e=>setOldBilling(e.target.value)}><option value="unknown">미확인</option><option value="stop">전환일부터 추가 청구 없음 확인</option><option value="through">지정한 마지막 청구일까지 유지</option><option value="keep">기존 조건대로 계속 청구</option></select></label>{oldBilling==='through'&&dateField('oldLastChargeDate','기존 계약 마지막 청구일 · 당일 포함',seed.oldLastChargeDate,true)}<label className="field">기존 서비스 이용 가능 기간<select value={oldAccess} onChange={e=>setOldAccess(e.target.value)}><option value="unknown">미확인</option><option value="ends">종료일 확인</option><option value="continues">비교 종료일까지 계속 이용</option></select></label>{oldAccess==='ends'&&dateField('oldAccessUntil','기존 서비스 이용 종료일',seed.oldAccessUntil,true)}</div><p className="note">이용 종료일과 마지막 청구일은 다를 수 있습니다. 이미 낸 연 요금은 겹친 이용 비용으로 다시 더하지 않습니다.</p></section>
 <details className="comparison-details"><summary>수수료·일할 추가 정산·확인된 환불</summary><p className="note">실제 기록에 포함된 수수료는 다시 넣지 마세요. 이미 발생한 환불은 원장 기록을 연결하세요.</p>{adjustments.map((ad,i)=><fieldset className="comparison-adjustment" key={ad.id}><legend>추가 금액 {i+1}</legend><div className="form-grid"><label className="field">대상안<select value={ad.scenario} onChange={e=>setAdjustments(xs=>xs.map(x=>x.id===ad.id?{...x,scenario:e.target.value as 'keep'|'change'}:x))}><option value="change">변경안</option><option value="keep">유지안</option></select></label><label className="field">종류<select value={ad.type} onChange={e=>setAdjustments(xs=>xs.map(x=>x.id===ad.id?{...x,type:e.target.value as typeof ad.type,recordedPaymentId:''}:x))}><option value="fee">전환 수수료</option><option value="proration">일할 추가 정산</option><option value="refund">환불</option></select></label>{ad.type==='refund'&&<label className="field wide">이미 기록된 환불<select value={ad.recordedPaymentId||''} onChange={e=>setAdjustments(xs=>xs.map(x=>x.id===ad.id?{...x,recordedPaymentId:e.target.value}:x))}><option value="">앞으로 받을 환불 직접 입력</option>{payments.filter(p=>p.payload.entryType==='refund').map(p=><option key={p.id} value={p.id}>{p.payload.date} · {money(p.payload.amount,p.payload.currency)}</option>)}</select></label>}{!ad.recordedPaymentId&&<><label className="field">추가 금액 통화<select value={ad.currency} onChange={e=>setAdjustments(xs=>xs.map(x=>x.id===ad.id?{...x,currency:e.target.value as typeof ad.currency}:x))}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label>{moneyField(ad.id+'Amount','금액',ad.amount,ad.currency)}{dateField(ad.id+'Date','발생 예정일',ad.date)}<label className="field">근거<input name={ad.id+'Source'} defaultValue={ad.source} maxLength={500}/></label></>}</div>{ad.recordedPaymentId?<p className="note">원장에 있는 환불을 연결했습니다. 두 안의 실제 기록에 한 번만 반영합니다.</p>:<label className="check-label"><input type="checkbox" name={ad.id+'Confirmed'} defaultChecked={ad.confirmed}/>금액·일정·적용 조건을 확인했습니다.</label>}<button type="button" className="button ghost small" onClick={()=>{setAdjustments(xs=>xs.filter(x=>x.id!==ad.id));clear();}}>항목 삭제</button></fieldset>)}<button type="button" className="button secondary small" disabled={adjustments.length>=40} onClick={()=>{setAdjustments(xs=>[...xs,{id:crypto.randomUUID(),type:'fee',scenario:'change',date:null,amount:null,currency:candidateCurrency as 'KRW',confirmed:false,source:''}]);clear();}}><Plus size={14}/>추가 금액 입력</button></details>
 <label className="check-label comparison-check"><input type="checkbox" name="extrasConfirmed" defaultChecked={seed.extrasConfirmed}/>추가 비용·환불·일할 정산을 확인했습니다. 없는 항목은 추가 금액 없음이 확인된 상태입니다.</label>
 <details className="comparison-details"><summary>필수 기능·이용 기간·선결제 조건</summary><div className="form-grid">{answerField('keepFit','유지안: 필수 기능·사용량·전체 이용 기간')}{answerField('changeFit','변경안: 필수 기능·사용량·전체 이용 기간')}{answerField('eligibility','새 요금·할인 적용 자격 (제한 없음 포함)')}{answerField('changeWilling','서비스·결제 경로를 바꿀 의향')}{currencies.map(c=><div key={c}>{moneyField('budget'+c,'한 번에 준비 가능한 금액',seed.criteria.budgets[c],c)}</div>)}</div><p className="note">비용이 낮아도 필요한 기능이나 이용 기간을 충족하지 못하면 추천하지 않습니다. 준비 금액은 같은 날의 총청구액과 비교합니다.</p></details>
 {error&&!preview&&<p className="error" role="alert">{error}</p>}<div className="actions"><button className="button primary" disabled={busy}>날짜별 비용 비교</button><button className="button ghost" type="button" onClick={()=>{onSaved();clear();toast('최신 계약·결제 기록을 불러옵니다.');}}>계약·결제 새로 불러오기</button></div>
 </form>
 {preview&&<><CostComparisonResult result={preview.result}/><form className="panel" onSubmit={save}><h3>이 비교 저장</h3><p className="note">현재 입력·계산 결과와 근거를 개인 기록에 보관합니다. 저장만으로 실제 계약이 변경되지는 않습니다.</p><label className="field">비교 제목<input name="title" required maxLength={200} defaultValue={((selected?.payload.name||'구독')+' → '+preview.conditions.candidate.name).slice(0,200)}/></label>{noteFields()}{error&&<p className="error" role="alert">{error}</p>}<button className="button secondary" disabled={busy}><Save size={15}/>{busy?'저장 중…':'조건과 결과 저장'}</button></form></>}
 </>}
 <section className="line-section"><div className="section-heading"><h3>저장한 요금 비교 <span className="metadata">{saved.length}개</span></h3></div>{saved.length?saved.map(r=>{const p=r.payload,source=subs.find(s=>s.id===p.subscriptionId),changed=source?.payload.historyId!==p.source.historyId||source?.payload.termsHistory?.revision!==p.source.revision;return <article className="saved-comparison" key={r.id}><div className="section-heading"><div><h4>{p.title}</h4><p>{p.conditions.from} – {p.conditions.until} · {decisions[p.decision as keyof typeof decisions]} · 저장 {r.created_at.slice(0,10)}</p></div><div className="actions"><button type="button" className="button ghost small" onClick={()=>setOpened(opened===r.id?null:r.id)} aria-expanded={opened===r.id}>저장 당시 결과</button><button type="button" className="icon-button" aria-label={p.title+' 비교 삭제'} onClick={()=>setDeleting(r)}><Trash2 size={15}/></button></div></div>{changed&&<p className="note">{source?'원계약·결제 기록이 변경되었습니다. 저장 당시 결과를 유지합니다.':'원계약이 삭제되었습니다. 저장한 조건과 결과는 확인할 수 있습니다.'}</p>}{p.reason&&<p>선택 이유: {p.reason}</p>}{p.outcome&&<p>결과: {p.outcome}</p>}{opened===r.id&&<><CostComparisonResult result={p.result}/><details className="comparison-details"><summary>저장한 비교 조건</summary><ComparisonConditions conditions={p.conditions} contracts={p.source.contracts}/></details><form onSubmit={e=>annotate(e,r)}>{noteFields(p)}<div className="actions"><button className="button secondary small" disabled={busy}>선택 기록 저장</button><button type="button" className="button ghost small" disabled={!source} onClick={()=>loadSaved(r)}>현재 조건으로 다시 비교</button></div></form></>}</article>;}):<p className="note">비교 결과에서 선택 이유와 함께 저장할 수 있습니다.</p>}</section>
 <details className="comparison-details simple-comparison"><summary>월·연 결제 간단 계산</summary><SimpleSavings/></details>
 {deleting&&<Modal title="요금 비교 삭제" onClose={()=>setDeleting(null)}><p>‘{deleting.payload.title}’ 비교 기록을 삭제할까요?</p><div className="actions"><button className="button danger" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/api/cost-comparisons',{method:'POST',body:JSON.stringify({action:'delete',id:deleting.id})});setDeleting(null);onSaved();toast('비교 기록을 삭제했습니다.');}catch(e){toast((e as Error).message);}finally{setBusy(false);}}}>삭제하기</button><button className="button ghost" onClick={()=>setDeleting(null)}>취소</button></div></Modal>}
 </div>;
}
