'use client';
import Link from '@/components/Link';
import {usePathname} from 'next/navigation';
import {useState,useRef,useEffect} from 'react';
import {useApp} from './Provider';
import Feedback from './Feedback';
import {Search,Menu,X,ArrowRight,Layers} from './Icons';
const isCurrent=(href:string,path:string)=>href==='/'?path==='/':path.startsWith(href)||href==='/explore'&&path.startsWith('/tools');
const nav=[['/','발견'],['/explore','도구 탐색'],['/news','소식·행사'],['/community','커뮤니티'],['/my','마이페이지']];
export function Header(){const path=usePathname(),[open,setOpen]=useState(false),{user}=useApp(),menuRef=useRef<HTMLElement>(null),toggleRef=useRef<HTMLButtonElement>(null);useEffect(()=>{if(open)menuRef.current?.querySelector<HTMLAnchorElement>('a')?.focus();},[open]);return <><a className="skip" href="#main">본문으로 이동</a><header className="site-header" onKeyDown={e=>{if(open&&e.key==='Escape'){e.preventDefault();setOpen(false);toggleRef.current?.focus();}}} onBlur={e=>{if(open&&!e.currentTarget.contains(e.relatedTarget as Node))setOpen(false);}}><div className="header-inner"><Link href="/" className="brand" aria-label="AIs 홈">AIs<span/></Link><nav id="primary-navigation" ref={menuRef} aria-label="주 메뉴" className={open?'open':''}>{nav.map(([href,label])=><Link key={href} href={href} onClick={()=>setOpen(false)} className={isCurrent(href,path)?'active':''} aria-current={isCurrent(href,path)?'page':undefined}>{label}</Link>)}</nav><div className="header-actions"><Link className="icon-button" href="/search" aria-label="전체 검색"><Search size={19}/></Link>{user?<Link href="/my" className="account-button">내 계정</Link>:<a className="account-button" href="/signin-with-chatgpt?return_to=/my" target="_top">로그인</a>}<button ref={toggleRef} className="mobile-menu icon-button" aria-controls="primary-navigation" aria-label="메뉴" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X size={22}/>:<Menu size={22}/>}</button></div></div></header></>;}
export function Footer(){return <footer className="site-footer"><div className="footer-inner"><Link className="brand small" href="/">AIs<span/></Link><p>AI·SaaS를 이해하고, 나에게 맞게.</p><div><Link href="/about">소개·평가 기준</Link><Link href="/cancellation">구독 해지 안내</Link><Link href="/privacy">개인정보</Link><Link href="/sources">출처·갱신 현황</Link><Feedback/></div></div></footer>;}
export function CompareDock(){const {compare,toggleCompare}=useApp(),path=usePathname();if(!compare.length||path==='/compare')return null;return <aside className="compare-dock" aria-label="비교 목록"><Layers size={19}/><span>비교할 도구 <strong>{compare.length}/3</strong></span><Link className="button primary small" href={'/compare?ids='+compare.join(',')}>비교하기<ArrowRight size={16}/></Link><button className="icon-button" aria-label="비교 목록 비우기" onClick={()=>compare.forEach(toggleCompare)}><X size={18}/></button></aside>;}
