'use client';
import {useState} from 'react';
import {comparePeriods,transitionComparison,toMinor,money} from '@/lib/billing';
type Result=ReturnType<typeof comparePeriods>&{adjustedAnnual?:number;complete?:boolean};
export default function Savings(){
 const [v,setV]=useState({monthly:'',annual:'',duration:'12',currency:'KRW',limit:'',overlap:'',transition:'',refund:''}),[features,setFeatures]=useState(false),[switching,setSwitching]=useState(false),[result,setResult]=useState<Result|null>(null),[error,setError]=useState('');
 function edit(key:keyof typeof v,value:string){setV({...v,[key]:value});setResult(null);}
 const amount=(key:keyof typeof v,label:string,required=false)=><label className="field" key={key}>{label}<input inputMode="decimal" required={required} value={v[key]} onChange={e=>edit(key,e.target.value)} placeholder={required?'':'미확인: 빈칸 · 없음 확인: 0'}/></label>;
 return <><div className="section-heading"><div><h2>동일 기간의 요금 비교</h2><p>월 결제와 연 결제의 지출을 같은 사용 기간으로 비교합니다.</p></div></div>
 <form className="panel" onSubmit={e=>{e.preventDefault();setResult(null);setError('');try{if(!features)throw new Error('필수 기능과 사용량 한도를 확인해주세요.');const args=[toMinor(v.monthly,v.currency),toMinor(v.annual,v.currency),Number(v.duration)] as const,limit=v.limit.trim()===''?null:toMinor(v.limit,v.currency),cost=(key:'overlap'|'transition'|'refund')=>v[key].trim()===''?null:toMinor(v[key],v.currency);setResult(switching?transitionComparison(...args,{overlap:cost('overlap'),transition:cost('transition'),refund:cost('refund')},limit):comparePeriods(...args,limit));}catch(e){setError((e as Error).message);}}}>
 <div className="form-grid">{amount('monthly','월 결제 금액 *',true)}{amount('annual','연 결제 금액 · 1년 총액 *',true)}<label className="field">사용 예정 기간 (개월)<input type="number" min={1} max={120} required value={v.duration} onChange={e=>edit('duration',e.target.value)}/></label><label className="field">통화<select value={v.currency} onChange={e=>edit('currency',e.target.value)}>{['KRW','USD','EUR','JPY'].map(c=><option key={c}>{c}</option>)}</select></label>{amount('limit','한 번에 준비할 수 있는 금액')}</div>
 <label className="check-label" style={{marginBottom:20}}><input type="checkbox" checked={features} onChange={e=>{setFeatures(e.target.checked);setResult(null);}}/>필수 기능과 사용량 한도가 두 플랜에 모두 충족됩니다.</label>
 <details style={{marginBottom:20}}><summary>전환 비용까지 비교하기</summary><label className="check-label" style={{margin:'18px 0'}}><input type="checkbox" checked={switching} onChange={e=>{setSwitching(e.target.checked);setResult(null);}}/>월 결제를 유지하는 경우와 연 결제로 전환하는 경우 비교</label>{switching&&<><div className="form-grid">{amount('overlap','기간 내 기존 계약 잔여·중복 청구')}{amount('transition','기간 내 데이터 이전·전환 비용')}{amount('refund','기간 내 확정된 환불액')}</div><p className="note">선택한 기간에 발생하는 추가 금액만 한 번 입력하세요. 연 요금에 포함된 비용은 다시 더하지 않습니다. 환불은 확인된 금액만 차감하며, 선결제 여력에는 보수적으로 반영하지 않습니다.</p></>}</details>
 {error&&<p className="error" role="alert">{error}</p>}<button className="button primary">총액 비교</button></form>
 {result&&<section className="section" aria-live="polite"><div className="money-grid"><div className="money-card"><small>{v.duration}개월 · 월 결제 유지</small><strong>{money(result.monthlyTotal,v.currency)}</strong></div><div className="money-card"><small>{v.duration}개월 · {switching?'전환 후 확인된 지출':'필요한 연 결제 총액'}</small><strong>{money(result.adjustedAnnual??result.annualTotal,v.currency)}</strong></div></div>
 {result.complete===false&&<p className="note warning" style={{marginTop:15}}>추가 비용·환불 중 미확인 항목이 있습니다. 확인된 금액만 비교했으며 최종 절약액과 실행 가능한 선택은 미확인입니다.</p>}
 <div className="note" style={{marginTop:15}}><strong>{result.difference===0?'확인된 총액이 같습니다.':`${result.recommended==='monthly'?'월 결제 유지':'연 결제'}가 확인된 금액 기준 ${money(Math.abs(result.difference),v.currency)} 적습니다.`}</strong><p style={{marginTop:8}}>{result.feasibleRecommendation?`입력한 준비 금액 안에서는 ${result.feasibleRecommendation==='monthly'?'월 결제':'연 결제'}를 선택할 수 있습니다.`:result.complete===false?'전환 조건 확인이 필요합니다.':v.limit.trim()===''?'준비 가능한 금액을 입력하면 선결제 가능 여부도 확인합니다.':'두 방식 모두 준비 가능한 금액을 초과합니다.'}{result.annualEligible===false&&' 연 결제는 입력한 한도를 초과합니다.'}</p><p style={{marginTop:8}}>{switching?'전환 비용을 포함해 보수적으로 준비할 금액':'연 결제 첫 선결제'}: {money(result.upfront,v.currency)}. 연 단위 결제는 필요한 전체 연수를 청구하며 중도 일할 환불을 자동으로 가정하지 않습니다.</p></div></section>}
 <p className="note" style={{marginTop:24}}>직접 확인한 요금을 입력하는 비교 계산입니다. 세금·환율·할인 조건은 입력 금액에 반영해 확인하세요. 자동 결제·해지·환불을 실행하지 않습니다.</p></>;
}
