'use client';
import {useState} from 'react';
import {activeTerms,supersededTerms,contractAmount,fromMinor,horizonEndDate,money,summarizeContracts,toMinor,today,type Contract,type Terms,type TermsHistory,type TermsVersion} from '@/lib/billing';
import {api} from './Provider';
import type {PrivateRecord} from './RecordForm';
const choices={currency:{KRW:'KRW · 원',USD:'USD · 달러',EUR:'EUR · 유로',JPY:'JPY · 엔'},cycle:{monthly:'매월',quarterly:'3개월마다',annual:'매년',custom:'개월 수 지정',manual:'다음 1회만'},status:{active:'갱신 중',cancel_requested:'해지 신청',cancelled:'해지 확인',ended:'종료',paused:'일시중지',unknown:'확인 필요'},amountBasis:{total:'계약 전체',perSeat:'좌석당',unknown:'확인 필요'},taxStatus:{included:'세금 포함',excluded:'세금 별도',unknown:'확인 필요'},pricingMode:{fixed:'고정 요금',usage:'사용량 청구',hybrid:'기본료 + 사용량'},pauseBilling:{continues:'청구 계속',stops:'청구 중단 확인',unknown:'확인 필요'}};
const amountKeys=['amount','personalShare','taxAmount','usageBudget'] as const;
export default function TermsEditor({record,onSaved}:{record:PrivateRecord;onSaved:()=>void}){
 const history=record.payload.termsHistory as TermsHistory|undefined;
 const current=history?activeTerms(history).filter(v=>v.effectiveFrom!<=today()).at(-1):null;
 const [editing,setEditing]=useState(false),[selected,setSelected]=useState<TermsVersion|null>(null),[values,setValues]=useState<Record<string,any>>({}),[effectiveFrom,setEffectiveFrom]=useState(''),[reason,setReason]=useState(''),[sourceNote,setSourceNote]=useState(''),[alreadyChanged,setAlreadyChanged]=useState(false),[amounts,setAmounts]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<ReturnType<typeof summarizeContracts>|null>(null);
 function start(version:TermsVersion|null){const t=version?.terms||current?.terms||record.payload;setValues({...t});setSelected(version);setEffectiveFrom(version?.effectiveFrom||'');setReason('');setSourceNote(version?.sourceNote||'');setAlreadyChanged(false);setAmounts(Object.fromEntries(amountKeys.map(k=>[k,t[k]!=null?String(fromMinor(t[k],t.currency)):'' ])));setPreview(null);setError('');setEditing(true);}
 function update(key:string,value:any){setValues(v=>({...v,[key]:value}));setPreview(null);}
 function proposal(form?:HTMLFormElement|null){const result={...values};if(form){const data=new FormData(form);for(const key of ['anchorDate','nextDate','endDate','remainingFromDate','resumeDate'])if(data.has(key))result[key]=String(data.get(key)||'');}for(const k of amountKeys)result[k]=amounts[k]?.trim()?toMinor(amounts[k],values.currency):null;for(const k of ['cycleMonths','seats','remainingPayments'])result[k]=values[k]===''||values[k]==null?null:Number(values[k]);return result as Terms;}
 function check(form:HTMLFormElement){try{const effective=String(new FormData(form).get('effectiveFrom')||''),terms=proposal(form),v:TermsVersion={id:'preview',effectiveFrom:effective||null,recordedAt:new Date().toISOString(),state:effective?'confirmed':'draft',terms,reason,...selected?{supersedes:selected.id}:{},...alreadyChanged&&!effective?{uncertainFrom:today()}:{}};const next:TermsHistory=history?{...history,knownFrom:effective&&selected===history.versions[0]?effective:history.knownFrom,versions:[...history.versions,v]}:{schemaVersion:1,revision:0,knownFrom:effective||today(),versions:[v]};setPreview(summarizeContracts([{id:record.id,...record.payload,termsHistory:next} as Contract],today(),horizonEndDate(today(),12)));setError('');}catch(e){setError((e as Error).message);}}
 async function save(action:'append'|'correct'|'void',target=selected,form?:HTMLFormElement){setBusy(true);setError('');try{await api('/api/billing-terms',{method:'POST',body:JSON.stringify({subscriptionId:record.id,expectedRevision:history?.revision??0,historyId:record.payload.historyId,action,supersedes:action==='append'?undefined:target?.id,effectiveFrom:(form?String(new FormData(form).get('effectiveFrom')||''):effectiveFrom)||null,terms:action==='void'?undefined:proposal(form),reason:action==='void'?'미적용 조건 철회':reason,sourceNote,alreadyChanged})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function initialize(){setBusy(true);setError('');try{await api('/api/billing-terms',{method:'POST',body:JSON.stringify({subscriptionId:record.id,expectedRevision:0,action:'initialize',reason:'기록일 기준 현재 조건'})});onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const field=(key:string,label:string,type='text')=><label className="field">{label}<input type={type} name={key} {...type==='date'?{defaultValue:values[key]??''}:{value:values[key]??''}} onChange={e=>update(key,e.target.value)} maxLength={100}/></label>;
 const choice=(key:keyof typeof choices,label:string)=><label className="field">{label}<select value={values[key]??''} onChange={e=>update(key,e.target.value)}>{Object.entries(choices[key]).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label>;
 const amount=(key:typeof amountKeys[number],label:string)=><label className="field">{label}<input inputMode="decimal" value={amounts[key]||''} onChange={e=>{setAmounts(a=>({...a,[key]:e.target.value}));setPreview(null);}} placeholder="미확인: 빈칸"/><small>{values.currency} · 0은 없음 확인</small></label>;
 const replaced=history?supersededTerms(history):new Set<string>();
 return <div className="terms-editor"><p className="note">{record.payload.name} · {record.payload.bundleId?'같은 번들 전체에 적용됩니다.':'이 계약의 조건을 날짜별로 보관합니다.'} 실제 결제·환불 기록은 각 기록의 금액과 통화를 유지합니다.</p>
 {error&&<p className="error" role="alert">{error}</p>}
 {!editing?<><div className="section-heading" style={{marginTop:24}}><h3>조건 이력</h3><button className="button primary small" disabled={busy} onClick={()=>history?start(null):initialize()}>{history?'변경 조건 추가':'현재 조건 기록'}</button></div>
 {!history&&<p className="note warning">이전 기록의 적용일을 알 수 없습니다. 먼저 현재 조건을 확인해 기록하고, 정확한 시작일을 알면 최초 이력을 정정하세요.</p>}
 <ol className="terms-timeline">{history?.versions.slice().reverse().map(v=>{const amount=contractAmount({id:record.id,...v.terms} as Contract,v.effectiveFrom||today()),obsolete=replaced.has(v.id);return <li key={v.id}><div className="section-heading"><strong>{v.effectiveFrom||'적용일 미확인'} <span className={'badge '+(obsolete||v.state==='void'?'gray':v.state==='draft'?'yellow':'blue')}>{obsolete?'정정된 이력':v.state==='void'?'철회 기록':v.state==='draft'?'검토 대기':v.basis==='observed'?'기록일 기준':v.effectiveFrom!>today()?'적용 예정':'확인한 조건'}</span></strong>{!obsolete&&v.state!=='void'&&<div className="actions"><button className="button ghost small" onClick={()=>start(v)}>정정</button>{(v.state==='draft'||v.effectiveFrom!>today())&&<button className="button ghost small" disabled={busy} onClick={()=>save('void',v)}>철회</button>}</div>}</div><p>{v.terms.plan||'요금제 미입력'} · {amount==null?'금액 미확인':money(amount,v.terms.currency)} / {choices.cycle[v.terms.cycle]}{v.terms.personalShare!=null?' · 예상 내 부담 '+money(v.terms.personalShare,v.terms.currency):''}</p><p>{v.reason}</p>{v.sourceNote&&<p className="metadata">{v.sourceNote}</p>}<small className="metadata">기록 {v.recordedAt.slice(0,10)}{v.basis==='observed'?' · 이전 기간의 조건은 확인되지 않았습니다.':''}</small></li>;})}</ol></>:<form onSubmit={e=>{e.preventDefault();save(selected?'correct':'append',selected,e.currentTarget);}}><div className="section-heading" style={{marginTop:20}}><h3>{selected?'기록 정정':'변경 조건'}</h3><button className="button ghost small" type="button" onClick={()=>setEditing(false)}>이력으로</button></div>
 <div className="form-grid"><label className="field">새 조건 적용일<input type="date" name="effectiveFrom" defaultValue={effectiveFrom} onInput={e=>{setEffectiveFrom(e.currentTarget.value);setPreview(null);}} onBlur={e=>setEffectiveFrom(e.currentTarget.value)} onChange={e=>{setEffectiveFrom(e.target.value);setPreview(null);}}/><small>모르면 빈칸 · 적용 전까지 이전 조건 유지</small></label>{field('plan','요금제')}
 {!effectiveFrom&&<label className="checkbox-label wide"><input type="checkbox" checked={alreadyChanged} onChange={e=>{setAlreadyChanged(e.target.checked);setPreview(null);}}/>이미 변경되었으나 적용일을 모름 · 오늘 이후 금액을 미확인으로 처리</label>}
 {amount('amount','회당 금액')}{choice('currency','통화')}{choice('cycle','결제 주기')}{values.cycle==='custom'&&field('cycleMonths','간격 (개월)','number')}{field('anchorDate','주기 기준 결제일','date')}{field('nextDate','이 조건의 첫 청구일','date')}{choice('status','계약 상태')}{field('endDate','이용 종료일','date')}{field('remainingPayments','확인한 잔여 청구 횟수','number')}{field('remainingFromDate','잔여 횟수를 세기 시작할 청구일','date')}
 {values.status==='paused'&&<>{choice('pauseBilling','일시중지 중 청구')}{field('resumeDate','확인한 청구 재개일','date')}</>}
 </div><details style={{margin:'16px 0'}}><summary>좌석·세금·내 부담액</summary><div className="form-grid" style={{marginTop:18}}>{choice('amountBasis','금액 기준')}{field('seats','좌석 수','number')}{choice('taxStatus','세금')}{amount('taxAmount','별도 세액 · 계약 전체')}{amount('personalShare','회당 예상 내 부담액')}{choice('pricingMode','과금 방식')}{amount('usageBudget','사용량 예산 · 청구 예상 제외')}</div></details>
 <div className="form-grid"><label className="field wide">변경·정정 사유 *<input required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} placeholder="예: 10월 갱신부터 요금제 변경"/></label><label className="field wide">확인 출처·메모<input maxLength={500} value={sourceNote} onChange={e=>setSourceNote(e.target.value)} placeholder="예: 결제 설정 화면에서 확인"/></label></div>
 <p className="note">가격만 바꾸면 첫 청구일과 기준일을 유지하세요. 주기를 바꿀 때는 새 조건의 첫 청구일을 입력하세요. 잔여 횟수의 기준일을 옮기면 그 날짜부터 횟수를 다시 셉니다. 정정 전 기록도 이력에 남습니다.</p>
 <div className="actions" style={{marginTop:18}}><button type="button" className="button secondary" onClick={e=>check(e.currentTarget.form!)}>12개월 청구 미리보기</button><button className="button primary" disabled={busy}>{busy?'저장 중':'조건 저장'}</button></div>
 {preview&&<div className="panel" style={{marginTop:20}}><h3>오늘부터 12개월</h3>{preview.conflictingHistory>0?<p className="error" role="alert">같은 적용일의 조건이 있어 예상 금액을 계산할 수 없습니다. 기존 이력을 정정하거나 새 조건의 적용일을 바꿔주세요.</p>:<><p>{Object.entries(preview.currencies).map(([c,v])=>money(v.expected,c)).join(' · ')||'확인된 예상 금액 없음'}</p><p className="note">예정 청구 기준 · 실제 결제 연결 전 · 미확인 금액 {preview.unknownFutureAmounts}회 · 검토 대기 {preview.pendingTerms}건</p><ul className="bullets">{preview.schedule.slice(0,12).map(d=><li key={d.date}>{d.date} · {d.amount==null?'금액 미확인':money(d.amount,d.currency)}</li>)}</ul></>}</div>}
 </form>}
 </div>;
}
