'use client';
import Link from '@/components/Link';
import {useState,useEffect} from 'react';
import {api} from './Provider';
import type {Tool} from '@/lib/catalog';
import {ArrowRight} from './Icons';
export const ratingAxes={quality:'결과 품질',efficiency:'작업 효율',korean:'한국어',value:'비용 대비',workflow:'작업 연결'};
type Scores={axes:Record<string,{value:number;count:number}>;sample:number;tasks:string[];plans:string[];latest:string|null};
export default function ToolReviews({tool}:{tool:Tool}){const [scores,setScores]=useState<Scores|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[task,setTask]=useState(''),[plan,setPlan]=useState('');useEffect(()=>{let alive=true;setError('');setLoading(true);api<Scores>('/api/scores?tool='+tool.id+'&task='+encodeURIComponent(task)+'&plan='+encodeURIComponent(plan)).then(s=>{if(alive)setScores(s);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[tool.id,task,plan]);return <><div className="section-heading"><h2 style={{margin:0}}>업무별 평가</h2><Link href={'/community?write=review&tool='+tool.id} className="text-link">평가 작성<ArrowRight size={14}/></Link></div><div className="note" style={{marginBottom:18}}>검수된 직접 평가 <strong>미평가</strong> · 아래 점수는 사용자가 입력한 경험입니다. 성능 실험 결과와 구분해서 확인하세요.</div><p className="sr-only" role="status">{loading?'평가를 불러오고 있습니다.':error?'평가를 불러오지 못했습니다.':(scores?.sample||0)+'명의 사용자 평가를 표시합니다.'}</p>{error?<div className="error" role="alert">{error}<button className="button ghost small" onClick={()=>location.reload()}>다시 불러오기</button></div>:!scores?<p className="loading">평가를 불러오고 있습니다.</p>:<><div className="filters" style={{margin:'10px 0 21px'}}><select aria-label="평가 업무" value={task} onChange={e=>setTask(e.target.value)}><option value="">모든 업무</option>{scores.tasks.map(t=><option key={t}>{t}</option>)}</select><select aria-label="평가 요금제" value={plan} onChange={e=>setPlan(e.target.value)}><option value="">모든 요금제</option>{scores.plans.map(p=><option key={p}>{p}</option>)}</select><span className="badge gray">사용자 평가 {scores.sample}명</span></div><div className="score-grid" aria-busy={loading}>{Object.entries(ratingAxes).map(([id,label])=><div className="score-row" key={id}><span>{label}{scores.axes[id]&&<small className="metadata">{scores.axes[id].count}명 응답</small>}</span><div className="score-track"><span style={{width:(scores.axes[id]?.value||0)*20+'%'}}/></div><strong>{scores.axes[id]?scores.axes[id].value.toFixed(1)+' / 5':'미평가'}</strong></div>)}</div><div className="score-meta">계정·도구별 최신 후기 1건 집계 · 항목별 응답 수는 다를 수 있습니다.</div>{scores.sample===0&&<p style={{fontSize:12}}>아직 이 조건의 사용자 평가가 없습니다. 사용 업무와 플랜을 함께 남겨주세요.</p>}</>}<Link className="text-link" style={{marginTop:15}} href={'/community?tool='+tool.id}>후기와 질문 보기<ArrowRight size={15}/></Link></>;}
